// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

type AuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLogRepository) EXPECT() *AuditLogRepository_Expecter {
	return &AuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *AuditLogRepository) Create(ctx context.Context, log *entity.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.AuditLog
func (_e *AuditLogRepository_Expecter) Create(ctx interface{}, log interface{}) *AuditLogRepository_Create_Call {
	return &AuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *AuditLogRepository_Create_Call) Run(run func(ctx context.Context, log *entity.AuditLog)) *AuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuditLog))
	})
	return _c
}

func (_c *AuditLogRepository_Create_Call) Return(_a0 error) *AuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.AuditLog) error) *AuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, limit, offset
func (_m *AuditLogRepository) List(ctx context.Context, orgID uuid.UUID, limit int, offset int) ([]entity.AuditLog, error) {
	ret := _m.Called(ctx, orgID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.AuditLog, error)); ok {
		return rf(ctx, orgID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.AuditLog); ok {
		r0 = rf(ctx, orgID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, orgID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - limit int
//   - offset int
func (_e *AuditLogRepository_Expecter) List(ctx interface{}, orgID interface{}, limit interface{}, offset interface{}) *AuditLogRepository_List_Call {
	return &AuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, orgID, limit, offset)}
}

func (_c *AuditLogRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, limit int, offset int)) *AuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *AuditLogRepository_List_Call) Return(_a0 []entity.AuditLog, _a1 error) *AuditLogRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditLogRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.AuditLog, error)) *AuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
