// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/username/sekre-backend/internal/application/auth"

	entity "github.com/username/sekre-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

type AuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthUsecase) EXPECT() *AuthUsecase_Expecter {
	return &AuthUsecase_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx, userID
func (_m *AuthUsecase) GetMe(ctx context.Context, userID uuid.UUID) (*entity.UserWithOrganization, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *entity.UserWithOrganization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserWithOrganization, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserWithOrganization); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserWithOrganization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type AuthUsecase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthUsecase_Expecter) GetMe(ctx interface{}, userID interface{}) *AuthUsecase_GetMe_Call {
	return &AuthUsecase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, userID)}
}

func (_c *AuthUsecase_GetMe_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthUsecase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthUsecase_GetMe_Call) Return(_a0 *entity.UserWithOrganization, _a1 error) *AuthUsecase_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_GetMe_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserWithOrganization, error)) *AuthUsecase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthUsecase) Login(ctx context.Context, req *auth.LoginRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) (*auth.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) *auth.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.LoginRequest
func (_e *AuthUsecase_Expecter) Login(ctx interface{}, req interface{}) *AuthUsecase_Login_Call {
	return &AuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *AuthUsecase_Login_Call) Run(run func(ctx context.Context, req *auth.LoginRequest)) *AuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.LoginRequest))
	})
	return _c
}

func (_c *AuthUsecase_Login_Call) Return(_a0 *auth.AuthResponse, _a1 error) *AuthUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_Login_Call) RunAndReturn(run func(context.Context, *auth.LoginRequest) (*auth.AuthResponse, error)) *AuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthUsecase) Register(ctx context.Context, req *auth.RegisterRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) (*auth.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) *auth.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.RegisterRequest
func (_e *AuthUsecase_Expecter) Register(ctx interface{}, req interface{}) *AuthUsecase_Register_Call {
	return &AuthUsecase_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *AuthUsecase_Register_Call) Run(run func(ctx context.Context, req *auth.RegisterRequest)) *AuthUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RegisterRequest))
	})
	return _c
}

func (_c *AuthUsecase_Register_Call) Return(_a0 *auth.AuthResponse, _a1 error) *AuthUsecase_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUsecase_Register_Call) RunAndReturn(run func(context.Context, *auth.RegisterRequest) (*auth.AuthResponse, error)) *AuthUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
