// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// DivisionMemberRepository is an autogenerated mock type for the DivisionMemberRepository type
type DivisionMemberRepository struct {
	mock.Mock
}

type DivisionMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DivisionMemberRepository) EXPECT() *DivisionMemberRepository_Expecter {
	return &DivisionMemberRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, orgID, member
func (_m *DivisionMemberRepository) AddMember(ctx context.Context, orgID uuid.UUID, member *entity.DivisionMember) error {
	ret := _m.Called(ctx, orgID, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.DivisionMember) error); ok {
		r0 = rf(ctx, orgID, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionMemberRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type DivisionMemberRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - member *entity.DivisionMember
func (_e *DivisionMemberRepository_Expecter) AddMember(ctx interface{}, orgID interface{}, member interface{}) *DivisionMemberRepository_AddMember_Call {
	return &DivisionMemberRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, orgID, member)}
}

func (_c *DivisionMemberRepository_AddMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, member *entity.DivisionMember)) *DivisionMemberRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.DivisionMember))
	})
	return _c
}

func (_c *DivisionMemberRepository_AddMember_Call) Return(_a0 error) *DivisionMemberRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionMemberRepository_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.DivisionMember) error) *DivisionMemberRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, orgID, divisionID
func (_m *DivisionMemberRepository) GetMembers(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.UserWithRole, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []entity.UserWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.UserWithRole); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionMemberRepository_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type DivisionMemberRepository_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *DivisionMemberRepository_Expecter) GetMembers(ctx interface{}, orgID interface{}, divisionID interface{}) *DivisionMemberRepository_GetMembers_Call {
	return &DivisionMemberRepository_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, orgID, divisionID)}
}

func (_c *DivisionMemberRepository_GetMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *DivisionMemberRepository_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionMemberRepository_GetMembers_Call) Return(_a0 []entity.UserWithRole, _a1 error) *DivisionMemberRepository_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionMemberRepository_GetMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)) *DivisionMemberRepository_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, divisionID, userID
func (_m *DivisionMemberRepository) RemoveMember(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, divisionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionMemberRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type DivisionMemberRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
func (_e *DivisionMemberRepository_Expecter) RemoveMember(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}) *DivisionMemberRepository_RemoveMember_Call {
	return &DivisionMemberRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, divisionID, userID)}
}

func (_c *DivisionMemberRepository_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID)) *DivisionMemberRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionMemberRepository_RemoveMember_Call) Return(_a0 error) *DivisionMemberRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionMemberRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *DivisionMemberRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, orgID, divisionID, userID, role
func (_m *DivisionMemberRepository) UpdateRole(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, orgID, divisionID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionMemberRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type DivisionMemberRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *DivisionMemberRepository_Expecter) UpdateRole(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}, role interface{}) *DivisionMemberRepository_UpdateRole_Call {
	return &DivisionMemberRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, orgID, divisionID, userID, role)}
}

func (_c *DivisionMemberRepository_UpdateRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string)) *DivisionMemberRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *DivisionMemberRepository_UpdateRole_Call) Return(_a0 error) *DivisionMemberRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionMemberRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error) *DivisionMemberRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewDivisionMemberRepository creates a new instance of DivisionMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDivisionMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DivisionMemberRepository {
	mock := &DivisionMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
