// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// DivisionRepository is an autogenerated mock type for the DivisionRepository type
type DivisionRepository struct {
	mock.Mock
}

type DivisionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DivisionRepository) EXPECT() *DivisionRepository_Expecter {
	return &DivisionRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, divisionID, userID, role
func (_m *DivisionRepository) AddMember(ctx context.Context, divisionID uuid.UUID, userID uuid.UUID, role types.DivisionRole) error {
	ret := _m.Called(ctx, divisionID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.DivisionRole) error); ok {
		r0 = rf(ctx, divisionID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type DivisionRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - divisionID uuid.UUID
//   - userID uuid.UUID
//   - role types.DivisionRole
func (_e *DivisionRepository_Expecter) AddMember(ctx interface{}, divisionID interface{}, userID interface{}, role interface{}) *DivisionRepository_AddMember_Call {
	return &DivisionRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, divisionID, userID, role)}
}

func (_c *DivisionRepository_AddMember_Call) Run(run func(ctx context.Context, divisionID uuid.UUID, userID uuid.UUID, role types.DivisionRole)) *DivisionRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.DivisionRole))
	})
	return _c
}

func (_c *DivisionRepository_AddMember_Call) Return(_a0 error) *DivisionRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.DivisionRole) error) *DivisionRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CountByOrganization provides a mock function with given fields: ctx, orgID
func (_m *DivisionRepository) CountByOrganization(ctx context.Context, orgID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CountByOrganization")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_CountByOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByOrganization'
type DivisionRepository_CountByOrganization_Call struct {
	*mock.Call
}

// CountByOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *DivisionRepository_Expecter) CountByOrganization(ctx interface{}, orgID interface{}) *DivisionRepository_CountByOrganization_Call {
	return &DivisionRepository_CountByOrganization_Call{Call: _e.mock.On("CountByOrganization", ctx, orgID)}
}

func (_c *DivisionRepository_CountByOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *DivisionRepository_CountByOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_CountByOrganization_Call) Return(_a0 int, _a1 error) *DivisionRepository_CountByOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_CountByOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *DivisionRepository_CountByOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CountHeads provides a mock function with given fields: ctx, divisionID
func (_m *DivisionRepository) CountHeads(ctx context.Context, divisionID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for CountHeads")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, divisionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_CountHeads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountHeads'
type DivisionRepository_CountHeads_Call struct {
	*mock.Call
}

// CountHeads is a helper method to define mock.On call
//   - ctx context.Context
//   - divisionID uuid.UUID
func (_e *DivisionRepository_Expecter) CountHeads(ctx interface{}, divisionID interface{}) *DivisionRepository_CountHeads_Call {
	return &DivisionRepository_CountHeads_Call{Call: _e.mock.On("CountHeads", ctx, divisionID)}
}

func (_c *DivisionRepository_CountHeads_Call) Run(run func(ctx context.Context, divisionID uuid.UUID)) *DivisionRepository_CountHeads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_CountHeads_Call) Return(_a0 int, _a1 error) *DivisionRepository_CountHeads_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_CountHeads_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *DivisionRepository_CountHeads_Call {
	_c.Call.Return(run)
	return _c
}

// CountMembers provides a mock function with given fields: ctx, divisionID
func (_m *DivisionRepository) CountMembers(ctx context.Context, divisionID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for CountMembers")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, divisionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_CountMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMembers'
type DivisionRepository_CountMembers_Call struct {
	*mock.Call
}

// CountMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - divisionID uuid.UUID
func (_e *DivisionRepository_Expecter) CountMembers(ctx interface{}, divisionID interface{}) *DivisionRepository_CountMembers_Call {
	return &DivisionRepository_CountMembers_Call{Call: _e.mock.On("CountMembers", ctx, divisionID)}
}

func (_c *DivisionRepository_CountMembers_Call) Run(run func(ctx context.Context, divisionID uuid.UUID)) *DivisionRepository_CountMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_CountMembers_Call) Return(_a0 int, _a1 error) *DivisionRepository_CountMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_CountMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *DivisionRepository_CountMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orgID, division
func (_m *DivisionRepository) Create(ctx context.Context, orgID uuid.UUID, division *entity.Division) error {
	ret := _m.Called(ctx, orgID, division)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Division) error); ok {
		r0 = rf(ctx, orgID, division)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DivisionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - division *entity.Division
func (_e *DivisionRepository_Expecter) Create(ctx interface{}, orgID interface{}, division interface{}) *DivisionRepository_Create_Call {
	return &DivisionRepository_Create_Call{Call: _e.mock.On("Create", ctx, orgID, division)}
}

func (_c *DivisionRepository_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, division *entity.Division)) *DivisionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Division))
	})
	return _c
}

func (_c *DivisionRepository_Create_Call) Return(_a0 error) *DivisionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Division) error) *DivisionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, divisionID
func (_m *DivisionRepository) Delete(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DivisionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *DivisionRepository_Expecter) Delete(ctx interface{}, orgID interface{}, divisionID interface{}) *DivisionRepository_Delete_Call {
	return &DivisionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, divisionID)}
}

func (_c *DivisionRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *DivisionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_Delete_Call) Return(_a0 error) *DivisionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *DivisionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, divisionID
func (_m *DivisionRepository) GetByID(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) (*entity.Division, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Division, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Division); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DivisionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *DivisionRepository_Expecter) GetByID(ctx interface{}, orgID interface{}, divisionID interface{}) *DivisionRepository_GetByID_Call {
	return &DivisionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, divisionID)}
}

func (_c *DivisionRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *DivisionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_GetByID_Call) Return(_a0 *entity.Division, _a1 error) *DivisionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Division, error)) *DivisionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNames provides a mock function with given fields: ctx, orgID, names
func (_m *DivisionRepository) GetByNames(ctx context.Context, orgID uuid.UUID, names []string) ([]entity.Division, error) {
	ret := _m.Called(ctx, orgID, names)

	if len(ret) == 0 {
		panic("no return value specified for GetByNames")
	}

	var r0 []entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]entity.Division, error)); ok {
		return rf(ctx, orgID, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []entity.Division); ok {
		r0 = rf(ctx, orgID, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, orgID, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_GetByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNames'
type DivisionRepository_GetByNames_Call struct {
	*mock.Call
}

// GetByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - names []string
func (_e *DivisionRepository_Expecter) GetByNames(ctx interface{}, orgID interface{}, names interface{}) *DivisionRepository_GetByNames_Call {
	return &DivisionRepository_GetByNames_Call{Call: _e.mock.On("GetByNames", ctx, orgID, names)}
}

func (_c *DivisionRepository_GetByNames_Call) Run(run func(ctx context.Context, orgID uuid.UUID, names []string)) *DivisionRepository_GetByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *DivisionRepository_GetByNames_Call) Return(_a0 []entity.Division, _a1 error) *DivisionRepository_GetByNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_GetByNames_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]entity.Division, error)) *DivisionRepository_GetByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, orgID, divisionID
func (_m *DivisionRepository) GetMembers(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.UserWithRole, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []entity.UserWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.UserWithRole); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type DivisionRepository_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *DivisionRepository_Expecter) GetMembers(ctx interface{}, orgID interface{}, divisionID interface{}) *DivisionRepository_GetMembers_Call {
	return &DivisionRepository_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, orgID, divisionID)}
}

func (_c *DivisionRepository_GetMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *DivisionRepository_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_GetMembers_Call) Return(_a0 []entity.UserWithRole, _a1 error) *DivisionRepository_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_GetMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)) *DivisionRepository_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersPaginated provides a mock function with given fields: ctx, orgID, divisionID, pagination
func (_m *DivisionRepository) GetMembersPaginated(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, pagination types.PaginationParams) ([]entity.UserWithRole, int, error) {
	ret := _m.Called(ctx, orgID, divisionID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersPaginated")
	}

	var r0 []entity.UserWithRole
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) ([]entity.UserWithRole, int, error)); ok {
		return rf(ctx, orgID, divisionID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) []entity.UserWithRole); ok {
		r0 = rf(ctx, orgID, divisionID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionRepository_GetMembersPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersPaginated'
type DivisionRepository_GetMembersPaginated_Call struct {
	*mock.Call
}

// GetMembersPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - pagination types.PaginationParams
func (_e *DivisionRepository_Expecter) GetMembersPaginated(ctx interface{}, orgID interface{}, divisionID interface{}, pagination interface{}) *DivisionRepository_GetMembersPaginated_Call {
	return &DivisionRepository_GetMembersPaginated_Call{Call: _e.mock.On("GetMembersPaginated", ctx, orgID, divisionID, pagination)}
}

func (_c *DivisionRepository_GetMembersPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, pagination types.PaginationParams)) *DivisionRepository_GetMembersPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.PaginationParams))
	})
	return _c
}

func (_c *DivisionRepository_GetMembersPaginated_Call) Return(_a0 []entity.UserWithRole, _a1 int, _a2 error) *DivisionRepository_GetMembersPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionRepository_GetMembersPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) ([]entity.UserWithRole, int, error)) *DivisionRepository_GetMembersPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserMemberOfDivision provides a mock function with given fields: ctx, orgID, divisionID, userID
func (_m *DivisionRepository) IsUserMemberOfDivision(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, orgID, divisionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserMemberOfDivision")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, orgID, divisionID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, orgID, divisionID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_IsUserMemberOfDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserMemberOfDivision'
type DivisionRepository_IsUserMemberOfDivision_Call struct {
	*mock.Call
}

// IsUserMemberOfDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
func (_e *DivisionRepository_Expecter) IsUserMemberOfDivision(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}) *DivisionRepository_IsUserMemberOfDivision_Call {
	return &DivisionRepository_IsUserMemberOfDivision_Call{Call: _e.mock.On("IsUserMemberOfDivision", ctx, orgID, divisionID, userID)}
}

func (_c *DivisionRepository_IsUserMemberOfDivision_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID)) *DivisionRepository_IsUserMemberOfDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_IsUserMemberOfDivision_Call) Return(_a0 bool, _a1 error) *DivisionRepository_IsUserMemberOfDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_IsUserMemberOfDivision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error)) *DivisionRepository_IsUserMemberOfDivision_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *DivisionRepository) List(ctx context.Context, orgID uuid.UUID) ([]entity.Division, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Division, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Division); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DivisionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *DivisionRepository_Expecter) List(ctx interface{}, orgID interface{}) *DivisionRepository_List_Call {
	return &DivisionRepository_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *DivisionRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *DivisionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_List_Call) Return(_a0 []entity.Division, _a1 error) *DivisionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Division, error)) *DivisionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function with given fields: ctx, orgID, pagination
func (_m *DivisionRepository) ListPaginated(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams) ([]entity.Division, int, error) {
	ret := _m.Called(ctx, orgID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []entity.Division
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.Division, int, error)); ok {
		return rf(ctx, orgID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) []entity.Division); ok {
		r0 = rf(ctx, orgID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type DivisionRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - pagination types.PaginationParams
func (_e *DivisionRepository_Expecter) ListPaginated(ctx interface{}, orgID interface{}, pagination interface{}) *DivisionRepository_ListPaginated_Call {
	return &DivisionRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, orgID, pagination)}
}

func (_c *DivisionRepository_ListPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams)) *DivisionRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.PaginationParams))
	})
	return _c
}

func (_c *DivisionRepository_ListPaginated_Call) Return(_a0 []entity.Division, _a1 int, _a2 error) *DivisionRepository_ListPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionRepository_ListPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.Division, int, error)) *DivisionRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, divisionID, userID
func (_m *DivisionRepository) RemoveMember(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, divisionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type DivisionRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
func (_e *DivisionRepository_Expecter) RemoveMember(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}) *DivisionRepository_RemoveMember_Call {
	return &DivisionRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, divisionID, userID)}
}

func (_c *DivisionRepository_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID)) *DivisionRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionRepository_RemoveMember_Call) Return(_a0 error) *DivisionRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *DivisionRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, division
func (_m *DivisionRepository) Update(ctx context.Context, orgID uuid.UUID, division *entity.Division) error {
	ret := _m.Called(ctx, orgID, division)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Division) error); ok {
		r0 = rf(ctx, orgID, division)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DivisionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - division *entity.Division
func (_e *DivisionRepository_Expecter) Update(ctx interface{}, orgID interface{}, division interface{}) *DivisionRepository_Update_Call {
	return &DivisionRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, division)}
}

func (_c *DivisionRepository_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, division *entity.Division)) *DivisionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Division))
	})
	return _c
}

func (_c *DivisionRepository_Update_Call) Return(_a0 error) *DivisionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Division) error) *DivisionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, orgID, divisionID, userID, role
func (_m *DivisionRepository) UpdateMemberRole(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, orgID, divisionID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type DivisionRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *DivisionRepository_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}, role interface{}) *DivisionRepository_UpdateMemberRole_Call {
	return &DivisionRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, divisionID, userID, role)}
}

func (_c *DivisionRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string)) *DivisionRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *DivisionRepository_UpdateMemberRole_Call) Return(_a0 error) *DivisionRepository_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error) *DivisionRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewDivisionRepository creates a new instance of DivisionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDivisionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DivisionRepository {
	mock := &DivisionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
