// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/username/sekre-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EventUsecase is an autogenerated mock type for the EventUsecase type
type EventUsecase struct {
	mock.Mock
}

type EventUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *EventUsecase) EXPECT() *EventUsecase_Expecter {
	return &EventUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orgID, _a2
func (_m *EventUsecase) Create(ctx context.Context, orgID uuid.UUID, _a2 *entity.Event) error {
	ret := _m.Called(ctx, orgID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Event) error); ok {
		r0 = rf(ctx, orgID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EventUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - _a2 *entity.Event
func (_e *EventUsecase_Expecter) Create(ctx interface{}, orgID interface{}, _a2 interface{}) *EventUsecase_Create_Call {
	return &EventUsecase_Create_Call{Call: _e.mock.On("Create", ctx, orgID, _a2)}
}

func (_c *EventUsecase_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, _a2 *entity.Event)) *EventUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Event))
	})
	return _c
}

func (_c *EventUsecase_Create_Call) Return(_a0 error) *EventUsecase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventUsecase_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Event) error) *EventUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, id
func (_m *EventUsecase) Delete(ctx context.Context, orgID uuid.UUID, id uuid.UUID) error {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EventUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *EventUsecase_Expecter) Delete(ctx interface{}, orgID interface{}, id interface{}) *EventUsecase_Delete_Call {
	return &EventUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, id)}
}

func (_c *EventUsecase_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *EventUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventUsecase_Delete_Call) Return(_a0 error) *EventUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventUsecase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *EventUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, id
func (_m *EventUsecase) GetByID(ctx context.Context, orgID uuid.UUID, id uuid.UUID) (*entity.Event, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Event, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Event); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type EventUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *EventUsecase_Expecter) GetByID(ctx interface{}, orgID interface{}, id interface{}) *EventUsecase_GetByID_Call {
	return &EventUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, id)}
}

func (_c *EventUsecase_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *EventUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventUsecase_GetByID_Call) Return(_a0 *entity.Event, _a1 error) *EventUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventUsecase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Event, error)) *EventUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, divisionID
func (_m *EventUsecase) List(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.Event, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Event, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.Event); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EventUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *EventUsecase_Expecter) List(ctx interface{}, orgID interface{}, divisionID interface{}) *EventUsecase_List_Call {
	return &EventUsecase_List_Call{Call: _e.mock.On("List", ctx, orgID, divisionID)}
}

func (_c *EventUsecase_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *EventUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventUsecase_List_Call) Return(_a0 []entity.Event, _a1 error) *EventUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventUsecase_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Event, error)) *EventUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, id, _a3
func (_m *EventUsecase) Update(ctx context.Context, orgID uuid.UUID, id uuid.UUID, _a3 *entity.Event) error {
	ret := _m.Called(ctx, orgID, id, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *entity.Event) error); ok {
		r0 = rf(ctx, orgID, id, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EventUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
//   - _a3 *entity.Event
func (_e *EventUsecase_Expecter) Update(ctx interface{}, orgID interface{}, id interface{}, _a3 interface{}) *EventUsecase_Update_Call {
	return &EventUsecase_Update_Call{Call: _e.mock.On("Update", ctx, orgID, id, _a3)}
}

func (_c *EventUsecase_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID, _a3 *entity.Event)) *EventUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*entity.Event))
	})
	return _c
}

func (_c *EventUsecase_Update_Call) Return(_a0 error) *EventUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventUsecase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *entity.Event) error) *EventUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventUsecase creates a new instance of EventUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventUsecase {
	mock := &EventUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
