// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

type EventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EventRepository) EXPECT() *EventRepository_Expecter {
	return &EventRepository_Expecter{mock: &_m.Mock}
}

// CountUpcomingByDivision provides a mock function with given fields: ctx, orgID, divisionID
func (_m *EventRepository) CountUpcomingByDivision(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for CountUpcomingByDivision")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventRepository_CountUpcomingByDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUpcomingByDivision'
type EventRepository_CountUpcomingByDivision_Call struct {
	*mock.Call
}

// CountUpcomingByDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *EventRepository_Expecter) CountUpcomingByDivision(ctx interface{}, orgID interface{}, divisionID interface{}) *EventRepository_CountUpcomingByDivision_Call {
	return &EventRepository_CountUpcomingByDivision_Call{Call: _e.mock.On("CountUpcomingByDivision", ctx, orgID, divisionID)}
}

func (_c *EventRepository_CountUpcomingByDivision_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *EventRepository_CountUpcomingByDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventRepository_CountUpcomingByDivision_Call) Return(_a0 int64, _a1 error) *EventRepository_CountUpcomingByDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventRepository_CountUpcomingByDivision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int64, error)) *EventRepository_CountUpcomingByDivision_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orgID, event
func (_m *EventRepository) Create(ctx context.Context, orgID uuid.UUID, event *entity.Event) error {
	ret := _m.Called(ctx, orgID, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Event) error); ok {
		r0 = rf(ctx, orgID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - event *entity.Event
func (_e *EventRepository_Expecter) Create(ctx interface{}, orgID interface{}, event interface{}) *EventRepository_Create_Call {
	return &EventRepository_Create_Call{Call: _e.mock.On("Create", ctx, orgID, event)}
}

func (_c *EventRepository_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, event *entity.Event)) *EventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Event))
	})
	return _c
}

func (_c *EventRepository_Create_Call) Return(_a0 error) *EventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Event) error) *EventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, eventID
func (_m *EventRepository) Delete(ctx context.Context, orgID uuid.UUID, eventID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - eventID uuid.UUID
func (_e *EventRepository_Expecter) Delete(ctx interface{}, orgID interface{}, eventID interface{}) *EventRepository_Delete_Call {
	return &EventRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, eventID)}
}

func (_c *EventRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, eventID uuid.UUID)) *EventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventRepository_Delete_Call) Return(_a0 error) *EventRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *EventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, eventID
func (_m *EventRepository) GetByID(ctx context.Context, orgID uuid.UUID, eventID uuid.UUID) (*entity.Event, error) {
	ret := _m.Called(ctx, orgID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Event, error)); ok {
		return rf(ctx, orgID, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Event); ok {
		r0 = rf(ctx, orgID, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type EventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - eventID uuid.UUID
func (_e *EventRepository_Expecter) GetByID(ctx interface{}, orgID interface{}, eventID interface{}) *EventRepository_GetByID_Call {
	return &EventRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, eventID)}
}

func (_c *EventRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, eventID uuid.UUID)) *EventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventRepository_GetByID_Call) Return(_a0 *entity.Event, _a1 error) *EventRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Event, error)) *EventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, divisionID
func (_m *EventRepository) List(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.Event, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Event, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.Event); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *EventRepository_Expecter) List(ctx interface{}, orgID interface{}, divisionID interface{}) *EventRepository_List_Call {
	return &EventRepository_List_Call{Call: _e.mock.On("List", ctx, orgID, divisionID)}
}

func (_c *EventRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *EventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *EventRepository_List_Call) Return(_a0 []entity.Event, _a1 error) *EventRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Event, error)) *EventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function with given fields: ctx, orgID, divisionID, pagination
func (_m *EventRepository) ListPaginated(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID, pagination types.PaginationParams) ([]entity.Event, int, error) {
	ret := _m.Called(ctx, orgID, divisionID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []entity.Event
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, types.PaginationParams) ([]entity.Event, int, error)); ok {
		return rf(ctx, orgID, divisionID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, types.PaginationParams) []entity.Event); ok {
		r0 = rf(ctx, orgID, divisionID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// EventRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type EventRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID *uuid.UUID
//   - pagination types.PaginationParams
func (_e *EventRepository_Expecter) ListPaginated(ctx interface{}, orgID interface{}, divisionID interface{}, pagination interface{}) *EventRepository_ListPaginated_Call {
	return &EventRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, orgID, divisionID, pagination)}
}

func (_c *EventRepository_ListPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID, pagination types.PaginationParams)) *EventRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID), args[3].(types.PaginationParams))
	})
	return _c
}

func (_c *EventRepository_ListPaginated_Call) Return(_a0 []entity.Event, _a1 int, _a2 error) *EventRepository_ListPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *EventRepository_ListPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID, types.PaginationParams) ([]entity.Event, int, error)) *EventRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, event
func (_m *EventRepository) Update(ctx context.Context, orgID uuid.UUID, event *entity.Event) error {
	ret := _m.Called(ctx, orgID, event)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Event) error); ok {
		r0 = rf(ctx, orgID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - event *entity.Event
func (_e *EventRepository_Expecter) Update(ctx interface{}, orgID interface{}, event interface{}) *EventRepository_Update_Call {
	return &EventRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, event)}
}

func (_c *EventRepository_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, event *entity.Event)) *EventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Event))
	})
	return _c
}

func (_c *EventRepository_Update_Call) Return(_a0 error) *EventRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Event) error) *EventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
