// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/username/sekre-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// FinanceUsecase is an autogenerated mock type for the FinanceUsecase type
type FinanceUsecase struct {
	mock.Mock
}

type FinanceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *FinanceUsecase) EXPECT() *FinanceUsecase_Expecter {
	return &FinanceUsecase_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: ctx, tx
func (_m *FinanceUsecase) CreateTransaction(ctx context.Context, tx *entity.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinanceUsecase_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type FinanceUsecase_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *entity.Transaction
func (_e *FinanceUsecase_Expecter) CreateTransaction(ctx interface{}, tx interface{}) *FinanceUsecase_CreateTransaction_Call {
	return &FinanceUsecase_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, tx)}
}

func (_c *FinanceUsecase_CreateTransaction_Call) Run(run func(ctx context.Context, tx *entity.Transaction)) *FinanceUsecase_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Transaction))
	})
	return _c
}

func (_c *FinanceUsecase_CreateTransaction_Call) Return(_a0 error) *FinanceUsecase_CreateTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FinanceUsecase_CreateTransaction_Call) RunAndReturn(run func(context.Context, *entity.Transaction) error) *FinanceUsecase_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, id
func (_m *FinanceUsecase) Delete(ctx context.Context, orgID uuid.UUID, id uuid.UUID) error {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinanceUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FinanceUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *FinanceUsecase_Expecter) Delete(ctx interface{}, orgID interface{}, id interface{}) *FinanceUsecase_Delete_Call {
	return &FinanceUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, id)}
}

func (_c *FinanceUsecase_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *FinanceUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *FinanceUsecase_Delete_Call) Return(_a0 error) *FinanceUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FinanceUsecase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *FinanceUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, id
func (_m *FinanceUsecase) GetByID(ctx context.Context, orgID uuid.UUID, id uuid.UUID) (*entity.Transaction, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Transaction, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Transaction); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinanceUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type FinanceUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *FinanceUsecase_Expecter) GetByID(ctx interface{}, orgID interface{}, id interface{}) *FinanceUsecase_GetByID_Call {
	return &FinanceUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, id)}
}

func (_c *FinanceUsecase_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *FinanceUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *FinanceUsecase_GetByID_Call) Return(_a0 *entity.Transaction, _a1 error) *FinanceUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FinanceUsecase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Transaction, error)) *FinanceUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function with given fields: ctx, orgID, divisionID
func (_m *FinanceUsecase) GetSummary(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID) (*entity.FinanceSummary, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *entity.FinanceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (*entity.FinanceSummary, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) *entity.FinanceSummary); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FinanceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinanceUsecase_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type FinanceUsecase_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID *uuid.UUID
func (_e *FinanceUsecase_Expecter) GetSummary(ctx interface{}, orgID interface{}, divisionID interface{}) *FinanceUsecase_GetSummary_Call {
	return &FinanceUsecase_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, orgID, divisionID)}
}

func (_c *FinanceUsecase_GetSummary_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID)) *FinanceUsecase_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *FinanceUsecase_GetSummary_Call) Return(_a0 *entity.FinanceSummary, _a1 error) *FinanceUsecase_GetSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FinanceUsecase_GetSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID) (*entity.FinanceSummary, error)) *FinanceUsecase_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, filters
func (_m *FinanceUsecase) List(ctx context.Context, orgID uuid.UUID, filters entity.TransactionFilters) ([]entity.Transaction, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TransactionFilters) ([]entity.Transaction, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TransactionFilters) []entity.Transaction); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.TransactionFilters) error); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinanceUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FinanceUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - filters entity.TransactionFilters
func (_e *FinanceUsecase_Expecter) List(ctx interface{}, orgID interface{}, filters interface{}) *FinanceUsecase_List_Call {
	return &FinanceUsecase_List_Call{Call: _e.mock.On("List", ctx, orgID, filters)}
}

func (_c *FinanceUsecase_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, filters entity.TransactionFilters)) *FinanceUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TransactionFilters))
	})
	return _c
}

func (_c *FinanceUsecase_List_Call) Return(_a0 []entity.Transaction, _a1 error) *FinanceUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FinanceUsecase_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.TransactionFilters) ([]entity.Transaction, error)) *FinanceUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, id, tx
func (_m *FinanceUsecase) Update(ctx context.Context, orgID uuid.UUID, id uuid.UUID, tx *entity.Transaction) error {
	ret := _m.Called(ctx, orgID, id, tx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *entity.Transaction) error); ok {
		r0 = rf(ctx, orgID, id, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinanceUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FinanceUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
//   - tx *entity.Transaction
func (_e *FinanceUsecase_Expecter) Update(ctx interface{}, orgID interface{}, id interface{}, tx interface{}) *FinanceUsecase_Update_Call {
	return &FinanceUsecase_Update_Call{Call: _e.mock.On("Update", ctx, orgID, id, tx)}
}

func (_c *FinanceUsecase_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID, tx *entity.Transaction)) *FinanceUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*entity.Transaction))
	})
	return _c
}

func (_c *FinanceUsecase_Update_Call) Return(_a0 error) *FinanceUsecase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FinanceUsecase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *entity.Transaction) error) *FinanceUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinanceUsecase creates a new instance of FinanceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceUsecase {
	mock := &FinanceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
