// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// InvitationRepository is an autogenerated mock type for the InvitationRepository type
type InvitationRepository struct {
	mock.Mock
}

type InvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationRepository) EXPECT() *InvitationRepository_Expecter {
	return &InvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, invitation
func (_m *InvitationRepository) Create(ctx context.Context, invitation *entity.Invitation) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Invitation) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *entity.Invitation
func (_e *InvitationRepository_Expecter) Create(ctx interface{}, invitation interface{}) *InvitationRepository_Create_Call {
	return &InvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, invitation)}
}

func (_c *InvitationRepository_Create_Call) Run(run func(ctx context.Context, invitation *entity.Invitation)) *InvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Invitation))
	})
	return _c
}

func (_c *InvitationRepository_Create_Call) Return(_a0 error) *InvitationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Invitation) error) *InvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *InvitationRepository) GetByToken(ctx context.Context, token string) (*entity.Invitation, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *entity.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Invitation, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Invitation); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type InvitationRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *InvitationRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *InvitationRepository_GetByToken_Call {
	return &InvitationRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *InvitationRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *InvitationRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InvitationRepository_GetByToken_Call) Return(_a0 *entity.Invitation, _a1 error) *InvitationRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*entity.Invitation, error)) *InvitationRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, invitationID, status
func (_m *InvitationRepository) UpdateStatus(ctx context.Context, invitationID uuid.UUID, status string) error {
	ret := _m.Called(ctx, invitationID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, invitationID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type InvitationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - invitationID uuid.UUID
//   - status string
func (_e *InvitationRepository_Expecter) UpdateStatus(ctx interface{}, invitationID interface{}, status interface{}) *InvitationRepository_UpdateStatus_Call {
	return &InvitationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, invitationID, status)}
}

func (_c *InvitationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, invitationID uuid.UUID, status string)) *InvitationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *InvitationRepository_UpdateStatus_Call) Return(_a0 error) *InvitationRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *InvitationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationRepository creates a new instance of InvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationRepository {
	mock := &InvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
