// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MemberCreationUsecase is an autogenerated mock type for the MemberCreationUsecase type
type MemberCreationUsecase struct {
	mock.Mock
}

type MemberCreationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberCreationUsecase) EXPECT() *MemberCreationUsecase_Expecter {
	return &MemberCreationUsecase_Expecter{mock: &_m.Mock}
}

// BulkImportMembers provides a mock function with given fields: ctx, members, orgID, actorID
func (_m *MemberCreationUsecase) BulkImportMembers(ctx context.Context, members []entity.BulkImportMemberRequest, orgID uuid.UUID, actorID uuid.UUID) (*entity.BulkImportResult, error) {
	ret := _m.Called(ctx, members, orgID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for BulkImportMembers")
	}

	var r0 *entity.BulkImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.BulkImportMemberRequest, uuid.UUID, uuid.UUID) (*entity.BulkImportResult, error)); ok {
		return rf(ctx, members, orgID, actorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.BulkImportMemberRequest, uuid.UUID, uuid.UUID) *entity.BulkImportResult); ok {
		r0 = rf(ctx, members, orgID, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BulkImportResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.BulkImportMemberRequest, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, members, orgID, actorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberCreationUsecase_BulkImportMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkImportMembers'
type MemberCreationUsecase_BulkImportMembers_Call struct {
	*mock.Call
}

// BulkImportMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - members []entity.BulkImportMemberRequest
//   - orgID uuid.UUID
//   - actorID uuid.UUID
func (_e *MemberCreationUsecase_Expecter) BulkImportMembers(ctx interface{}, members interface{}, orgID interface{}, actorID interface{}) *MemberCreationUsecase_BulkImportMembers_Call {
	return &MemberCreationUsecase_BulkImportMembers_Call{Call: _e.mock.On("BulkImportMembers", ctx, members, orgID, actorID)}
}

func (_c *MemberCreationUsecase_BulkImportMembers_Call) Run(run func(ctx context.Context, members []entity.BulkImportMemberRequest, orgID uuid.UUID, actorID uuid.UUID)) *MemberCreationUsecase_BulkImportMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.BulkImportMemberRequest), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MemberCreationUsecase_BulkImportMembers_Call) Return(_a0 *entity.BulkImportResult, _a1 error) *MemberCreationUsecase_BulkImportMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberCreationUsecase_BulkImportMembers_Call) RunAndReturn(run func(context.Context, []entity.BulkImportMemberRequest, uuid.UUID, uuid.UUID) (*entity.BulkImportResult, error)) *MemberCreationUsecase_BulkImportMembers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMember provides a mock function with given fields: ctx, req, orgID, actorID
func (_m *MemberCreationUsecase) CreateMember(ctx context.Context, req entity.CreateMemberRequest, orgID uuid.UUID, actorID uuid.UUID) (*entity.CreatedMemberInfo, error) {
	ret := _m.Called(ctx, req, orgID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateMember")
	}

	var r0 *entity.CreatedMemberInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateMemberRequest, uuid.UUID, uuid.UUID) (*entity.CreatedMemberInfo, error)); ok {
		return rf(ctx, req, orgID, actorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateMemberRequest, uuid.UUID, uuid.UUID) *entity.CreatedMemberInfo); ok {
		r0 = rf(ctx, req, orgID, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CreatedMemberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateMemberRequest, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, req, orgID, actorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberCreationUsecase_CreateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMember'
type MemberCreationUsecase_CreateMember_Call struct {
	*mock.Call
}

// CreateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity.CreateMemberRequest
//   - orgID uuid.UUID
//   - actorID uuid.UUID
func (_e *MemberCreationUsecase_Expecter) CreateMember(ctx interface{}, req interface{}, orgID interface{}, actorID interface{}) *MemberCreationUsecase_CreateMember_Call {
	return &MemberCreationUsecase_CreateMember_Call{Call: _e.mock.On("CreateMember", ctx, req, orgID, actorID)}
}

func (_c *MemberCreationUsecase_CreateMember_Call) Run(run func(ctx context.Context, req entity.CreateMemberRequest, orgID uuid.UUID, actorID uuid.UUID)) *MemberCreationUsecase_CreateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateMemberRequest), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MemberCreationUsecase_CreateMember_Call) Return(_a0 *entity.CreatedMemberInfo, _a1 error) *MemberCreationUsecase_CreateMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberCreationUsecase_CreateMember_Call) RunAndReturn(run func(context.Context, entity.CreateMemberRequest, uuid.UUID, uuid.UUID) (*entity.CreatedMemberInfo, error)) *MemberCreationUsecase_CreateMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberCreationUsecase creates a new instance of MemberCreationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberCreationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberCreationUsecase {
	mock := &MemberCreationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
