// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MemberUsecase is an autogenerated mock type for the MemberUsecase type
type MemberUsecase struct {
	mock.Mock
}

type MemberUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberUsecase) EXPECT() *MemberUsecase_Expecter {
	return &MemberUsecase_Expecter{mock: &_m.Mock}
}

// ListMembers provides a mock function with given fields: ctx, orgID
func (_m *MemberUsecase) ListMembers(ctx context.Context, orgID uuid.UUID) ([]entity.UserWithOrgRole, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []entity.UserWithOrgRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberUsecase_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MemberUsecase_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MemberUsecase_Expecter) ListMembers(ctx interface{}, orgID interface{}) *MemberUsecase_ListMembers_Call {
	return &MemberUsecase_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, orgID)}
}

func (_c *MemberUsecase_ListMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MemberUsecase_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MemberUsecase_ListMembers_Call) Return(_a0 []entity.UserWithOrgRole, _a1 error) *MemberUsecase_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberUsecase_ListMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)) *MemberUsecase_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, userID
func (_m *MemberUsecase) RemoveMember(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberUsecase_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MemberUsecase_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *MemberUsecase_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MemberUsecase_RemoveMember_Call {
	return &MemberUsecase_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MemberUsecase_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *MemberUsecase_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MemberUsecase_RemoveMember_Call) Return(_a0 error) *MemberUsecase_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberUsecase_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MemberUsecase_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, orgID, userID, role
func (_m *MemberUsecase) UpdateMemberRole(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, orgID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberUsecase_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MemberUsecase_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MemberUsecase_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, userID interface{}, role interface{}) *MemberUsecase_UpdateMemberRole_Call {
	return &MemberUsecase_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, userID, role)}
}

func (_c *MemberUsecase_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role string)) *MemberUsecase_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MemberUsecase_UpdateMemberRole_Call) Return(_a0 error) *MemberUsecase_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberUsecase_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MemberUsecase_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberUsecase creates a new instance of MemberUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberUsecase {
	mock := &MemberUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
