// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// MemberRepository is an autogenerated mock type for the MemberRepository type
type MemberRepository struct {
	mock.Mock
}

type MemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberRepository) EXPECT() *MemberRepository_Expecter {
	return &MemberRepository_Expecter{mock: &_m.Mock}
}

// AddMemberToDivision provides a mock function with given fields: ctx, divisionID, userID, divisionRole
func (_m *MemberRepository) AddMemberToDivision(ctx context.Context, divisionID uuid.UUID, userID uuid.UUID, divisionRole types.DivisionRole) error {
	ret := _m.Called(ctx, divisionID, userID, divisionRole)

	if len(ret) == 0 {
		panic("no return value specified for AddMemberToDivision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.DivisionRole) error); ok {
		r0 = rf(ctx, divisionID, userID, divisionRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_AddMemberToDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMemberToDivision'
type MemberRepository_AddMemberToDivision_Call struct {
	*mock.Call
}

// AddMemberToDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - divisionID uuid.UUID
//   - userID uuid.UUID
//   - divisionRole types.DivisionRole
func (_e *MemberRepository_Expecter) AddMemberToDivision(ctx interface{}, divisionID interface{}, userID interface{}, divisionRole interface{}) *MemberRepository_AddMemberToDivision_Call {
	return &MemberRepository_AddMemberToDivision_Call{Call: _e.mock.On("AddMemberToDivision", ctx, divisionID, userID, divisionRole)}
}

func (_c *MemberRepository_AddMemberToDivision_Call) Run(run func(ctx context.Context, divisionID uuid.UUID, userID uuid.UUID, divisionRole types.DivisionRole)) *MemberRepository_AddMemberToDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.DivisionRole))
	})
	return _c
}

func (_c *MemberRepository_AddMemberToDivision_Call) Return(_a0 error) *MemberRepository_AddMemberToDivision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_AddMemberToDivision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.DivisionRole) error) *MemberRepository_AddMemberToDivision_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToOrganization provides a mock function with given fields: ctx, orgID, userID, role
func (_m *MemberRepository) AddUserToOrganization(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role types.Role) error {
	ret := _m.Called(ctx, orgID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.Role) error); ok {
		r0 = rf(ctx, orgID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_AddUserToOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToOrganization'
type MemberRepository_AddUserToOrganization_Call struct {
	*mock.Call
}

// AddUserToOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - role types.Role
func (_e *MemberRepository_Expecter) AddUserToOrganization(ctx interface{}, orgID interface{}, userID interface{}, role interface{}) *MemberRepository_AddUserToOrganization_Call {
	return &MemberRepository_AddUserToOrganization_Call{Call: _e.mock.On("AddUserToOrganization", ctx, orgID, userID, role)}
}

func (_c *MemberRepository_AddUserToOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role types.Role)) *MemberRepository_AddUserToOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.Role))
	})
	return _c
}

func (_c *MemberRepository_AddUserToOrganization_Call) Return(_a0 error) *MemberRepository_AddUserToOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_AddUserToOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.Role) error) *MemberRepository_AddUserToOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuditLog provides a mock function with given fields: ctx, log
func (_m *MemberRepository) CreateAuditLog(ctx context.Context, log *entity.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MemberRepository_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.AuditLog
func (_e *MemberRepository_Expecter) CreateAuditLog(ctx interface{}, log interface{}) *MemberRepository_CreateAuditLog_Call {
	return &MemberRepository_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", ctx, log)}
}

func (_c *MemberRepository_CreateAuditLog_Call) Run(run func(ctx context.Context, log *entity.AuditLog)) *MemberRepository_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuditLog))
	})
	return _c
}

func (_c *MemberRepository_CreateAuditLog_Call) Return(_a0 error) *MemberRepository_CreateAuditLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_CreateAuditLog_Call) RunAndReturn(run func(context.Context, *entity.AuditLog) error) *MemberRepository_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MemberRepository) CreateUser(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MemberRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MemberRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MemberRepository_CreateUser_Call {
	return &MemberRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MemberRepository_CreateUser_Call) Run(run func(ctx context.Context, user *entity.User)) *MemberRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MemberRepository_CreateUser_Call) Return(_a0 error) *MemberRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MemberRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDivisionByName provides a mock function with given fields: ctx, orgID, name
func (_m *MemberRepository) GetDivisionByName(ctx context.Context, orgID uuid.UUID, name string) (*entity.Division, error) {
	ret := _m.Called(ctx, orgID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetDivisionByName")
	}

	var r0 *entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.Division, error)); ok {
		return rf(ctx, orgID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.Division); ok {
		r0 = rf(ctx, orgID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, orgID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_GetDivisionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDivisionByName'
type MemberRepository_GetDivisionByName_Call struct {
	*mock.Call
}

// GetDivisionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - name string
func (_e *MemberRepository_Expecter) GetDivisionByName(ctx interface{}, orgID interface{}, name interface{}) *MemberRepository_GetDivisionByName_Call {
	return &MemberRepository_GetDivisionByName_Call{Call: _e.mock.On("GetDivisionByName", ctx, orgID, name)}
}

func (_c *MemberRepository_GetDivisionByName_Call) Run(run func(ctx context.Context, orgID uuid.UUID, name string)) *MemberRepository_GetDivisionByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MemberRepository_GetDivisionByName_Call) Return(_a0 *entity.Division, _a1 error) *MemberRepository_GetDivisionByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_GetDivisionByName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entity.Division, error)) *MemberRepository_GetDivisionByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationMembers provides a mock function with given fields: ctx, orgID
func (_m *MemberRepository) GetOrganizationMembers(ctx context.Context, orgID uuid.UUID) ([]entity.UserWithOrgRole, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationMembers")
	}

	var r0 []entity.UserWithOrgRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_GetOrganizationMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationMembers'
type MemberRepository_GetOrganizationMembers_Call struct {
	*mock.Call
}

// GetOrganizationMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MemberRepository_Expecter) GetOrganizationMembers(ctx interface{}, orgID interface{}) *MemberRepository_GetOrganizationMembers_Call {
	return &MemberRepository_GetOrganizationMembers_Call{Call: _e.mock.On("GetOrganizationMembers", ctx, orgID)}
}

func (_c *MemberRepository_GetOrganizationMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MemberRepository_GetOrganizationMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MemberRepository_GetOrganizationMembers_Call) Return(_a0 []entity.UserWithOrgRole, _a1 error) *MemberRepository_GetOrganizationMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_GetOrganizationMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)) *MemberRepository_GetOrganizationMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationMembersPaginated provides a mock function with given fields: ctx, orgID, pagination
func (_m *MemberRepository) GetOrganizationMembersPaginated(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams) ([]entity.UserWithOrgRole, int, error) {
	ret := _m.Called(ctx, orgID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationMembersPaginated")
	}

	var r0 []entity.UserWithOrgRole
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.UserWithOrgRole, int, error)); ok {
		return rf(ctx, orgID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MemberRepository_GetOrganizationMembersPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationMembersPaginated'
type MemberRepository_GetOrganizationMembersPaginated_Call struct {
	*mock.Call
}

// GetOrganizationMembersPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - pagination types.PaginationParams
func (_e *MemberRepository_Expecter) GetOrganizationMembersPaginated(ctx interface{}, orgID interface{}, pagination interface{}) *MemberRepository_GetOrganizationMembersPaginated_Call {
	return &MemberRepository_GetOrganizationMembersPaginated_Call{Call: _e.mock.On("GetOrganizationMembersPaginated", ctx, orgID, pagination)}
}

func (_c *MemberRepository_GetOrganizationMembersPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams)) *MemberRepository_GetOrganizationMembersPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.PaginationParams))
	})
	return _c
}

func (_c *MemberRepository_GetOrganizationMembersPaginated_Call) Return(_a0 []entity.UserWithOrgRole, _a1 int, _a2 error) *MemberRepository_GetOrganizationMembersPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MemberRepository_GetOrganizationMembersPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.UserWithOrgRole, int, error)) *MemberRepository_GetOrganizationMembersPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: ctx, orgID, userID
func (_m *MemberRepository) IsMember(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MemberRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *MemberRepository_Expecter) IsMember(ctx interface{}, orgID interface{}, userID interface{}) *MemberRepository_IsMember_Call {
	return &MemberRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, orgID, userID)}
}

func (_c *MemberRepository_IsMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *MemberRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MemberRepository_IsMember_Call) Return(_a0 bool, _a1 error) *MemberRepository_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_IsMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MemberRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, userID
func (_m *MemberRepository) RemoveMember(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MemberRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *MemberRepository_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MemberRepository_RemoveMember_Call {
	return &MemberRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MemberRepository_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *MemberRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MemberRepository_RemoveMember_Call) Return(_a0 error) *MemberRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MemberRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, orgID, userID, role
func (_m *MemberRepository) UpdateMemberRole(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role types.Role) error {
	ret := _m.Called(ctx, orgID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.Role) error); ok {
		r0 = rf(ctx, orgID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MemberRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - role types.Role
func (_e *MemberRepository_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, userID interface{}, role interface{}) *MemberRepository_UpdateMemberRole_Call {
	return &MemberRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, userID, role)}
}

func (_c *MemberRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role types.Role)) *MemberRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.Role))
	})
	return _c
}

func (_c *MemberRepository_UpdateMemberRole_Call) Return(_a0 error) *MemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.Role) error) *MemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberRepository creates a new instance of MemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberRepository {
	mock := &MemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
