// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

type OrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationRepository) EXPECT() *OrganizationRepository_Expecter {
	return &OrganizationRepository_Expecter{mock: &_m.Mock}
}

// CheckSubdomainExists provides a mock function with given fields: ctx, subdomain
func (_m *OrganizationRepository) CheckSubdomainExists(ctx context.Context, subdomain string) (bool, error) {
	ret := _m.Called(ctx, subdomain)

	if len(ret) == 0 {
		panic("no return value specified for CheckSubdomainExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, subdomain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, subdomain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subdomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationRepository_CheckSubdomainExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckSubdomainExists'
type OrganizationRepository_CheckSubdomainExists_Call struct {
	*mock.Call
}

// CheckSubdomainExists is a helper method to define mock.On call
//   - ctx context.Context
//   - subdomain string
func (_e *OrganizationRepository_Expecter) CheckSubdomainExists(ctx interface{}, subdomain interface{}) *OrganizationRepository_CheckSubdomainExists_Call {
	return &OrganizationRepository_CheckSubdomainExists_Call{Call: _e.mock.On("CheckSubdomainExists", ctx, subdomain)}
}

func (_c *OrganizationRepository_CheckSubdomainExists_Call) Run(run func(ctx context.Context, subdomain string)) *OrganizationRepository_CheckSubdomainExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationRepository_CheckSubdomainExists_Call) Return(_a0 bool, _a1 error) *OrganizationRepository_CheckSubdomainExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationRepository_CheckSubdomainExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *OrganizationRepository_CheckSubdomainExists_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, org
func (_m *OrganizationRepository) Create(ctx context.Context, org *entity.Organization) error {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Organization) error); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrganizationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org *entity.Organization
func (_e *OrganizationRepository_Expecter) Create(ctx interface{}, org interface{}) *OrganizationRepository_Create_Call {
	return &OrganizationRepository_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *OrganizationRepository_Create_Call) Run(run func(ctx context.Context, org *entity.Organization)) *OrganizationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Organization))
	})
	return _c
}

func (_c *OrganizationRepository_Create_Call) Return(_a0 error) *OrganizationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Organization) error) *OrganizationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID
func (_m *OrganizationRepository) Delete(ctx context.Context, orgID uuid.UUID) error {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrganizationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *OrganizationRepository_Expecter) Delete(ctx interface{}, orgID interface{}) *OrganizationRepository_Delete_Call {
	return &OrganizationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID)}
}

func (_c *OrganizationRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *OrganizationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrganizationRepository_Delete_Call) Return(_a0 error) *OrganizationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrganizationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID
func (_m *OrganizationRepository) GetByID(ctx context.Context, orgID uuid.UUID) (*entity.Organization, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Organization, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Organization); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type OrganizationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *OrganizationRepository_Expecter) GetByID(ctx interface{}, orgID interface{}) *OrganizationRepository_GetByID_Call {
	return &OrganizationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID)}
}

func (_c *OrganizationRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *OrganizationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrganizationRepository_GetByID_Call) Return(_a0 *entity.Organization, _a1 error) *OrganizationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Organization, error)) *OrganizationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRole provides a mock function with given fields: ctx, orgID, userID
func (_m *OrganizationRepository) GetMemberRole(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (types.Role, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 types.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (types.Role, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) types.Role); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(types.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationRepository_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type OrganizationRepository_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *OrganizationRepository_Expecter) GetMemberRole(ctx interface{}, orgID interface{}, userID interface{}) *OrganizationRepository_GetMemberRole_Call {
	return &OrganizationRepository_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, orgID, userID)}
}

func (_c *OrganizationRepository_GetMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *OrganizationRepository_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *OrganizationRepository_GetMemberRole_Call) Return(_a0 types.Role, _a1 error) *OrganizationRepository_GetMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationRepository_GetMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (types.Role, error)) *OrganizationRepository_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, name
func (_m *OrganizationRepository) Update(ctx context.Context, orgID uuid.UUID, name string) (*entity.Organization, error) {
	ret := _m.Called(ctx, orgID, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.Organization, error)); ok {
		return rf(ctx, orgID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.Organization); ok {
		r0 = rf(ctx, orgID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, orgID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type OrganizationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - name string
func (_e *OrganizationRepository_Expecter) Update(ctx interface{}, orgID interface{}, name interface{}) *OrganizationRepository_Update_Call {
	return &OrganizationRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, name)}
}

func (_c *OrganizationRepository_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, name string)) *OrganizationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *OrganizationRepository_Update_Call) Return(_a0 *entity.Organization, _a1 error) *OrganizationRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entity.Organization, error)) *OrganizationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationRepository creates a new instance of OrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationRepository {
	mock := &OrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
