// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// PasswordResetRepository is an autogenerated mock type for the PasswordResetRepository type
type PasswordResetRepository struct {
	mock.Mock
}

type PasswordResetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordResetRepository) EXPECT() *PasswordResetRepository_Expecter {
	return &PasswordResetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, reset
func (_m *PasswordResetRepository) Create(ctx context.Context, reset *entity.PasswordReset) error {
	ret := _m.Called(ctx, reset)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PasswordReset) error); ok {
		r0 = rf(ctx, reset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordResetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PasswordResetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reset *entity.PasswordReset
func (_e *PasswordResetRepository_Expecter) Create(ctx interface{}, reset interface{}) *PasswordResetRepository_Create_Call {
	return &PasswordResetRepository_Create_Call{Call: _e.mock.On("Create", ctx, reset)}
}

func (_c *PasswordResetRepository_Create_Call) Run(run func(ctx context.Context, reset *entity.PasswordReset)) *PasswordResetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PasswordReset))
	})
	return _c
}

func (_c *PasswordResetRepository_Create_Call) Return(_a0 error) *PasswordResetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordResetRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.PasswordReset) error) *PasswordResetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *PasswordResetRepository) GetByToken(ctx context.Context, token string) (*entity.PasswordReset, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *entity.PasswordReset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.PasswordReset, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.PasswordReset); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PasswordReset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordResetRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type PasswordResetRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *PasswordResetRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *PasswordResetRepository_GetByToken_Call {
	return &PasswordResetRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *PasswordResetRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *PasswordResetRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PasswordResetRepository_GetByToken_Call) Return(_a0 *entity.PasswordReset, _a1 error) *PasswordResetRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordResetRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*entity.PasswordReset, error)) *PasswordResetRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsUsed provides a mock function with given fields: ctx, resetID
func (_m *PasswordResetRepository) MarkAsUsed(ctx context.Context, resetID uuid.UUID) error {
	ret := _m.Called(ctx, resetID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, resetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordResetRepository_MarkAsUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsUsed'
type PasswordResetRepository_MarkAsUsed_Call struct {
	*mock.Call
}

// MarkAsUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - resetID uuid.UUID
func (_e *PasswordResetRepository_Expecter) MarkAsUsed(ctx interface{}, resetID interface{}) *PasswordResetRepository_MarkAsUsed_Call {
	return &PasswordResetRepository_MarkAsUsed_Call{Call: _e.mock.On("MarkAsUsed", ctx, resetID)}
}

func (_c *PasswordResetRepository_MarkAsUsed_Call) Run(run func(ctx context.Context, resetID uuid.UUID)) *PasswordResetRepository_MarkAsUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PasswordResetRepository_MarkAsUsed_Call) Return(_a0 error) *PasswordResetRepository_MarkAsUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordResetRepository_MarkAsUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PasswordResetRepository_MarkAsUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordResetRepository creates a new instance of PasswordResetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordResetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordResetRepository {
	mock := &PasswordResetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
