// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RegistrationValidator is an autogenerated mock type for the RegistrationValidator type
type RegistrationValidator struct {
	mock.Mock
}

type RegistrationValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistrationValidator) EXPECT() *RegistrationValidator_Expecter {
	return &RegistrationValidator_Expecter{mock: &_m.Mock}
}

// ValidateEmail provides a mock function with given fields: email
func (_m *RegistrationValidator) ValidateEmail(email string) error {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistrationValidator_ValidateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEmail'
type RegistrationValidator_ValidateEmail_Call struct {
	*mock.Call
}

// ValidateEmail is a helper method to define mock.On call
//   - email string
func (_e *RegistrationValidator_Expecter) ValidateEmail(email interface{}) *RegistrationValidator_ValidateEmail_Call {
	return &RegistrationValidator_ValidateEmail_Call{Call: _e.mock.On("ValidateEmail", email)}
}

func (_c *RegistrationValidator_ValidateEmail_Call) Run(run func(email string)) *RegistrationValidator_ValidateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RegistrationValidator_ValidateEmail_Call) Return(_a0 error) *RegistrationValidator_ValidateEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistrationValidator_ValidateEmail_Call) RunAndReturn(run func(string) error) *RegistrationValidator_ValidateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePassword provides a mock function with given fields: password
func (_m *RegistrationValidator) ValidatePassword(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistrationValidator_ValidatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePassword'
type RegistrationValidator_ValidatePassword_Call struct {
	*mock.Call
}

// ValidatePassword is a helper method to define mock.On call
//   - password string
func (_e *RegistrationValidator_Expecter) ValidatePassword(password interface{}) *RegistrationValidator_ValidatePassword_Call {
	return &RegistrationValidator_ValidatePassword_Call{Call: _e.mock.On("ValidatePassword", password)}
}

func (_c *RegistrationValidator_ValidatePassword_Call) Run(run func(password string)) *RegistrationValidator_ValidatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RegistrationValidator_ValidatePassword_Call) Return(_a0 error) *RegistrationValidator_ValidatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistrationValidator_ValidatePassword_Call) RunAndReturn(run func(string) error) *RegistrationValidator_ValidatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSubdomain provides a mock function with given fields: subdomain
func (_m *RegistrationValidator) ValidateSubdomain(subdomain string) error {
	ret := _m.Called(subdomain)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSubdomain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(subdomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistrationValidator_ValidateSubdomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSubdomain'
type RegistrationValidator_ValidateSubdomain_Call struct {
	*mock.Call
}

// ValidateSubdomain is a helper method to define mock.On call
//   - subdomain string
func (_e *RegistrationValidator_Expecter) ValidateSubdomain(subdomain interface{}) *RegistrationValidator_ValidateSubdomain_Call {
	return &RegistrationValidator_ValidateSubdomain_Call{Call: _e.mock.On("ValidateSubdomain", subdomain)}
}

func (_c *RegistrationValidator_ValidateSubdomain_Call) Run(run func(subdomain string)) *RegistrationValidator_ValidateSubdomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RegistrationValidator_ValidateSubdomain_Call) Return(_a0 error) *RegistrationValidator_ValidateSubdomain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistrationValidator_ValidateSubdomain_Call) RunAndReturn(run func(string) error) *RegistrationValidator_ValidateSubdomain_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistrationValidator creates a new instance of RegistrationValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrationValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistrationValidator {
	mock := &RegistrationValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
