// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// CountActiveByDivision provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TaskRepository) CountActiveByDivision(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByDivision")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_CountActiveByDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByDivision'
type TaskRepository_CountActiveByDivision_Call struct {
	*mock.Call
}

// CountActiveByDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *TaskRepository_Expecter) CountActiveByDivision(ctx interface{}, orgID interface{}, divisionID interface{}) *TaskRepository_CountActiveByDivision_Call {
	return &TaskRepository_CountActiveByDivision_Call{Call: _e.mock.On("CountActiveByDivision", ctx, orgID, divisionID)}
}

func (_c *TaskRepository_CountActiveByDivision_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *TaskRepository_CountActiveByDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_CountActiveByDivision_Call) Return(_a0 int64, _a1 error) *TaskRepository_CountActiveByDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_CountActiveByDivision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int64, error)) *TaskRepository_CountActiveByDivision_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orgID, task
func (_m *TaskRepository) Create(ctx context.Context, orgID uuid.UUID, task *entity.Task) error {
	ret := _m.Called(ctx, orgID, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Task) error); ok {
		r0 = rf(ctx, orgID, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - task *entity.Task
func (_e *TaskRepository_Expecter) Create(ctx interface{}, orgID interface{}, task interface{}) *TaskRepository_Create_Call {
	return &TaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, orgID, task)}
}

func (_c *TaskRepository_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, task *entity.Task)) *TaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Task))
	})
	return _c
}

func (_c *TaskRepository_Create_Call) Return(_a0 error) *TaskRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Task) error) *TaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, taskID
func (_m *TaskRepository) Delete(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - taskID uuid.UUID
func (_e *TaskRepository_Expecter) Delete(ctx interface{}, orgID interface{}, taskID interface{}) *TaskRepository_Delete_Call {
	return &TaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, taskID)}
}

func (_c *TaskRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID)) *TaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_Delete_Call) Return(_a0 error) *TaskRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, taskID
func (_m *TaskRepository) GetByID(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID) (*entity.Task, error) {
	ret := _m.Called(ctx, orgID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Task, error)); ok {
		return rf(ctx, orgID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Task); ok {
		r0 = rf(ctx, orgID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - taskID uuid.UUID
func (_e *TaskRepository_Expecter) GetByID(ctx interface{}, orgID interface{}, taskID interface{}) *TaskRepository_GetByID_Call {
	return &TaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, taskID)}
}

func (_c *TaskRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID)) *TaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_GetByID_Call) Return(_a0 *entity.Task, _a1 error) *TaskRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Task, error)) *TaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithAssignee provides a mock function with given fields: ctx, orgID, taskID
func (_m *TaskRepository) GetByIDWithAssignee(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID) (*entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithAssignee")
	}

	var r0 *entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_GetByIDWithAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithAssignee'
type TaskRepository_GetByIDWithAssignee_Call struct {
	*mock.Call
}

// GetByIDWithAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - taskID uuid.UUID
func (_e *TaskRepository_Expecter) GetByIDWithAssignee(ctx interface{}, orgID interface{}, taskID interface{}) *TaskRepository_GetByIDWithAssignee_Call {
	return &TaskRepository_GetByIDWithAssignee_Call{Call: _e.mock.On("GetByIDWithAssignee", ctx, orgID, taskID)}
}

func (_c *TaskRepository_GetByIDWithAssignee_Call) Run(run func(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID)) *TaskRepository_GetByIDWithAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_GetByIDWithAssignee_Call) Return(_a0 *entity.TaskWithAssignee, _a1 error) *TaskRepository_GetByIDWithAssignee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_GetByIDWithAssignee_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.TaskWithAssignee, error)) *TaskRepository_GetByIDWithAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TaskRepository) List(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.Task, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Task, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.Task); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *TaskRepository_Expecter) List(ctx interface{}, orgID interface{}, divisionID interface{}) *TaskRepository_List_Call {
	return &TaskRepository_List_Call{Call: _e.mock.On("List", ctx, orgID, divisionID)}
}

func (_c *TaskRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *TaskRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_List_Call) Return(_a0 []entity.Task, _a1 error) *TaskRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Task, error)) *TaskRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiltered provides a mock function with given fields: ctx, orgID, filters
func (_m *TaskRepository) ListFiltered(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters) ([]entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListFiltered")
	}

	var r0 []entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters) ([]entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters) []entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.TaskFilters) error); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_ListFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiltered'
type TaskRepository_ListFiltered_Call struct {
	*mock.Call
}

// ListFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - filters entity.TaskFilters
func (_e *TaskRepository_Expecter) ListFiltered(ctx interface{}, orgID interface{}, filters interface{}) *TaskRepository_ListFiltered_Call {
	return &TaskRepository_ListFiltered_Call{Call: _e.mock.On("ListFiltered", ctx, orgID, filters)}
}

func (_c *TaskRepository_ListFiltered_Call) Run(run func(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters)) *TaskRepository_ListFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TaskFilters))
	})
	return _c
}

func (_c *TaskRepository_ListFiltered_Call) Return(_a0 []entity.TaskWithAssignee, _a1 error) *TaskRepository_ListFiltered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_ListFiltered_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.TaskFilters) ([]entity.TaskWithAssignee, error)) *TaskRepository_ListFiltered_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilteredPaginated provides a mock function with given fields: ctx, orgID, filters, pagination
func (_m *TaskRepository) ListFilteredPaginated(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters, pagination types.PaginationParams) ([]entity.TaskWithAssignee, int, error) {
	ret := _m.Called(ctx, orgID, filters, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListFilteredPaginated")
	}

	var r0 []entity.TaskWithAssignee
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters, types.PaginationParams) ([]entity.TaskWithAssignee, int, error)); ok {
		return rf(ctx, orgID, filters, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters, types.PaginationParams) []entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, filters, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.TaskFilters, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, filters, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, entity.TaskFilters, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, filters, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_ListFilteredPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilteredPaginated'
type TaskRepository_ListFilteredPaginated_Call struct {
	*mock.Call
}

// ListFilteredPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - filters entity.TaskFilters
//   - pagination types.PaginationParams
func (_e *TaskRepository_Expecter) ListFilteredPaginated(ctx interface{}, orgID interface{}, filters interface{}, pagination interface{}) *TaskRepository_ListFilteredPaginated_Call {
	return &TaskRepository_ListFilteredPaginated_Call{Call: _e.mock.On("ListFilteredPaginated", ctx, orgID, filters, pagination)}
}

func (_c *TaskRepository_ListFilteredPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters, pagination types.PaginationParams)) *TaskRepository_ListFilteredPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TaskFilters), args[3].(types.PaginationParams))
	})
	return _c
}

func (_c *TaskRepository_ListFilteredPaginated_Call) Return(_a0 []entity.TaskWithAssignee, _a1 int, _a2 error) *TaskRepository_ListFilteredPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_ListFilteredPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.TaskFilters, types.PaginationParams) ([]entity.TaskWithAssignee, int, error)) *TaskRepository_ListFilteredPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithAssignee provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TaskRepository) ListWithAssignee(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithAssignee")
	}

	var r0 []entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_ListWithAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithAssignee'
type TaskRepository_ListWithAssignee_Call struct {
	*mock.Call
}

// ListWithAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *TaskRepository_Expecter) ListWithAssignee(ctx interface{}, orgID interface{}, divisionID interface{}) *TaskRepository_ListWithAssignee_Call {
	return &TaskRepository_ListWithAssignee_Call{Call: _e.mock.On("ListWithAssignee", ctx, orgID, divisionID)}
}

func (_c *TaskRepository_ListWithAssignee_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *TaskRepository_ListWithAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskRepository_ListWithAssignee_Call) Return(_a0 []entity.TaskWithAssignee, _a1 error) *TaskRepository_ListWithAssignee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_ListWithAssignee_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.TaskWithAssignee, error)) *TaskRepository_ListWithAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, task
func (_m *TaskRepository) Update(ctx context.Context, orgID uuid.UUID, task *entity.Task) error {
	ret := _m.Called(ctx, orgID, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Task) error); ok {
		r0 = rf(ctx, orgID, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - task *entity.Task
func (_e *TaskRepository_Expecter) Update(ctx interface{}, orgID interface{}, task interface{}) *TaskRepository_Update_Call {
	return &TaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, task)}
}

func (_c *TaskRepository_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, task *entity.Task)) *TaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Task))
	})
	return _c
}

func (_c *TaskRepository_Update_Call) Return(_a0 error) *TaskRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Task) error) *TaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orgID, taskID, status
func (_m *TaskRepository) UpdateStatus(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID, status string) error {
	ret := _m.Called(ctx, orgID, taskID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, taskID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type TaskRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - taskID uuid.UUID
//   - status string
func (_e *TaskRepository_Expecter) UpdateStatus(ctx interface{}, orgID interface{}, taskID interface{}, status interface{}) *TaskRepository_UpdateStatus_Call {
	return &TaskRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orgID, taskID, status)}
}

func (_c *TaskRepository_UpdateStatus_Call) Run(run func(ctx context.Context, orgID uuid.UUID, taskID uuid.UUID, status string)) *TaskRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TaskRepository_UpdateStatus_Call) Return(_a0 error) *TaskRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *TaskRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
