// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	token "github.com/username/sekre-backend/pkg/token"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

type TokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGenerator) EXPECT() *TokenGenerator_Expecter {
	return &TokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: userID, organizationID, role
func (_m *TokenGenerator) Generate(userID uuid.UUID, organizationID uuid.UUID, role types.Role) (*token.TokenPair, error) {
	ret := _m.Called(userID, organizationID, role)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *token.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, types.Role) (*token.TokenPair, error)); ok {
		return rf(userID, organizationID, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, types.Role) *token.TokenPair); ok {
		r0 = rf(userID, organizationID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, types.Role) error); ok {
		r1 = rf(userID, organizationID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID uuid.UUID
//   - organizationID uuid.UUID
//   - role types.Role
func (_e *TokenGenerator_Expecter) Generate(userID interface{}, organizationID interface{}, role interface{}) *TokenGenerator_Generate_Call {
	return &TokenGenerator_Generate_Call{Call: _e.mock.On("Generate", userID, organizationID, role)}
}

func (_c *TokenGenerator_Generate_Call) Run(run func(userID uuid.UUID, organizationID uuid.UUID, role types.Role)) *TokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(types.Role))
	})
	return _c
}

func (_c *TokenGenerator_Generate_Call) Return(_a0 *token.TokenPair, _a1 error) *TokenGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenGenerator_Generate_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, types.Role) (*token.TokenPair, error)) *TokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: tokenString
func (_m *TokenGenerator) Verify(tokenString string) (*token.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *token.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*token.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *token.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenGenerator_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenGenerator_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - tokenString string
func (_e *TokenGenerator_Expecter) Verify(tokenString interface{}) *TokenGenerator_Verify_Call {
	return &TokenGenerator_Verify_Call{Call: _e.mock.On("Verify", tokenString)}
}

func (_c *TokenGenerator_Verify_Call) Run(run func(tokenString string)) *TokenGenerator_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenGenerator_Verify_Call) Return(_a0 *token.Claims, _a1 error) *TokenGenerator_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenGenerator_Verify_Call) RunAndReturn(run func(string) (*token.Claims, error)) *TokenGenerator_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
