// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// CountRecentByDivision provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TransactionRepository) CountRecentByDivision(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for CountRecentByDivision")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_CountRecentByDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRecentByDivision'
type TransactionRepository_CountRecentByDivision_Call struct {
	*mock.Call
}

// CountRecentByDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *TransactionRepository_Expecter) CountRecentByDivision(ctx interface{}, orgID interface{}, divisionID interface{}) *TransactionRepository_CountRecentByDivision_Call {
	return &TransactionRepository_CountRecentByDivision_Call{Call: _e.mock.On("CountRecentByDivision", ctx, orgID, divisionID)}
}

func (_c *TransactionRepository_CountRecentByDivision_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *TransactionRepository_CountRecentByDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_CountRecentByDivision_Call) Return(_a0 int64, _a1 error) *TransactionRepository_CountRecentByDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_CountRecentByDivision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int64, error)) *TransactionRepository_CountRecentByDivision_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orgID, transaction
func (_m *TransactionRepository) Create(ctx context.Context, orgID uuid.UUID, transaction *entity.Transaction) error {
	ret := _m.Called(ctx, orgID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Transaction) error); ok {
		r0 = rf(ctx, orgID, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - transaction *entity.Transaction
func (_e *TransactionRepository_Expecter) Create(ctx interface{}, orgID interface{}, transaction interface{}) *TransactionRepository_Create_Call {
	return &TransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, orgID, transaction)}
}

func (_c *TransactionRepository_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, transaction *entity.Transaction)) *TransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Create_Call) Return(_a0 error) *TransactionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Transaction) error) *TransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, transactionID
func (_m *TransactionRepository) Delete(ctx context.Context, orgID uuid.UUID, transactionID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, transactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TransactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - transactionID uuid.UUID
func (_e *TransactionRepository_Expecter) Delete(ctx interface{}, orgID interface{}, transactionID interface{}) *TransactionRepository_Delete_Call {
	return &TransactionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, transactionID)}
}

func (_c *TransactionRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, transactionID uuid.UUID)) *TransactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_Delete_Call) Return(_a0 error) *TransactionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TransactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, transactionID
func (_m *TransactionRepository) GetByID(ctx context.Context, orgID uuid.UUID, transactionID uuid.UUID) (*entity.Transaction, error) {
	ret := _m.Called(ctx, orgID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Transaction, error)); ok {
		return rf(ctx, orgID, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Transaction); ok {
		r0 = rf(ctx, orgID, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - transactionID uuid.UUID
func (_e *TransactionRepository_Expecter) GetByID(ctx interface{}, orgID interface{}, transactionID interface{}) *TransactionRepository_GetByID_Call {
	return &TransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, transactionID)}
}

func (_c *TransactionRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, transactionID uuid.UUID)) *TransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_GetByID_Call) Return(_a0 *entity.Transaction, _a1 error) *TransactionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Transaction, error)) *TransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TransactionRepository) GetSummary(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID) (*entity.FinanceSummary, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *entity.FinanceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (*entity.FinanceSummary, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) *entity.FinanceSummary); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FinanceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type TransactionRepository_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID *uuid.UUID
func (_e *TransactionRepository_Expecter) GetSummary(ctx interface{}, orgID interface{}, divisionID interface{}) *TransactionRepository_GetSummary_Call {
	return &TransactionRepository_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, orgID, divisionID)}
}

func (_c *TransactionRepository_GetSummary_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID *uuid.UUID)) *TransactionRepository_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_GetSummary_Call) Return(_a0 *entity.FinanceSummary, _a1 error) *TransactionRepository_GetSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID) (*entity.FinanceSummary, error)) *TransactionRepository_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, divisionID
func (_m *TransactionRepository) List(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.Transaction, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Transaction, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.Transaction); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TransactionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *TransactionRepository_Expecter) List(ctx interface{}, orgID interface{}, divisionID interface{}) *TransactionRepository_List_Call {
	return &TransactionRepository_List_Call{Call: _e.mock.On("List", ctx, orgID, divisionID)}
}

func (_c *TransactionRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *TransactionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_List_Call) Return(_a0 []entity.Transaction, _a1 error) *TransactionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.Transaction, error)) *TransactionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiltered provides a mock function with given fields: ctx, orgID, filters
func (_m *TransactionRepository) ListFiltered(ctx context.Context, orgID uuid.UUID, filters entity.TransactionFilters) ([]entity.Transaction, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListFiltered")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TransactionFilters) ([]entity.Transaction, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TransactionFilters) []entity.Transaction); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.TransactionFilters) error); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_ListFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiltered'
type TransactionRepository_ListFiltered_Call struct {
	*mock.Call
}

// ListFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - filters entity.TransactionFilters
func (_e *TransactionRepository_Expecter) ListFiltered(ctx interface{}, orgID interface{}, filters interface{}) *TransactionRepository_ListFiltered_Call {
	return &TransactionRepository_ListFiltered_Call{Call: _e.mock.On("ListFiltered", ctx, orgID, filters)}
}

func (_c *TransactionRepository_ListFiltered_Call) Run(run func(ctx context.Context, orgID uuid.UUID, filters entity.TransactionFilters)) *TransactionRepository_ListFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TransactionFilters))
	})
	return _c
}

func (_c *TransactionRepository_ListFiltered_Call) Return(_a0 []entity.Transaction, _a1 error) *TransactionRepository_ListFiltered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_ListFiltered_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.TransactionFilters) ([]entity.Transaction, error)) *TransactionRepository_ListFiltered_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, transaction
func (_m *TransactionRepository) Update(ctx context.Context, orgID uuid.UUID, transaction *entity.Transaction) error {
	ret := _m.Called(ctx, orgID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Transaction) error); ok {
		r0 = rf(ctx, orgID, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - transaction *entity.Transaction
func (_e *TransactionRepository_Expecter) Update(ctx interface{}, orgID interface{}, transaction interface{}) *TransactionRepository_Update_Call {
	return &TransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, transaction)}
}

func (_c *TransactionRepository_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, transaction *entity.Transaction)) *TransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Update_Call) Return(_a0 error) *TransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.Transaction) error) *TransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
