// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TxRunner is an autogenerated mock type for the TxRunner type
type TxRunner struct {
	mock.Mock
}

type TxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *TxRunner) EXPECT() *TxRunner_Expecter {
	return &TxRunner_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *TxRunner) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxRunner_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type TxRunner_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *TxRunner_Expecter) WithTransaction(ctx interface{}, fn interface{}) *TxRunner_WithTransaction_Call {
	return &TxRunner_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *TxRunner_WithTransaction_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *TxRunner_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *TxRunner_WithTransaction_Call) Return(_a0 error) *TxRunner_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxRunner_WithTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *TxRunner_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxRunner creates a new instance of TxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxRunner {
	mock := &TxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
