// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(_a0 *entity.User, _a1 error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *UserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, userID
func (_m *UserRepository) GetByID(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *UserRepository_Expecter) GetByID(ctx interface{}, orgID interface{}, userID interface{}) *UserRepository_GetByID_Call {
	return &UserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, userID)}
}

func (_c *UserRepository_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *UserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_GetByID_Call) Return(_a0 *entity.User, _a1 error) *UserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.User, error)) *UserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *UserRepository) List(ctx context.Context, orgID uuid.UUID) ([]entity.User, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.User, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.User); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *UserRepository_Expecter) List(ctx interface{}, orgID interface{}) *UserRepository_List_Call {
	return &UserRepository_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *UserRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *UserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_List_Call) Return(_a0 []entity.User, _a1 error) *UserRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.User, error)) *UserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByEmail provides a mock function with given fields: ctx, orgID, email
func (_m *UserRepository) SearchByEmail(ctx context.Context, orgID uuid.UUID, email string) ([]entity.UserBasic, error) {
	ret := _m.Called(ctx, orgID, email)

	if len(ret) == 0 {
		panic("no return value specified for SearchByEmail")
	}

	var r0 []entity.UserBasic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]entity.UserBasic, error)); ok {
		return rf(ctx, orgID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []entity.UserBasic); ok {
		r0 = rf(ctx, orgID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBasic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, orgID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_SearchByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByEmail'
type UserRepository_SearchByEmail_Call struct {
	*mock.Call
}

// SearchByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - email string
func (_e *UserRepository_Expecter) SearchByEmail(ctx interface{}, orgID interface{}, email interface{}) *UserRepository_SearchByEmail_Call {
	return &UserRepository_SearchByEmail_Call{Call: _e.mock.On("SearchByEmail", ctx, orgID, email)}
}

func (_c *UserRepository_SearchByEmail_Call) Run(run func(ctx context.Context, orgID uuid.UUID, email string)) *UserRepository_SearchByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_SearchByEmail_Call) Return(_a0 []entity.UserBasic, _a1 error) *UserRepository_SearchByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_SearchByEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]entity.UserBasic, error)) *UserRepository_SearchByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SetMustResetPassword provides a mock function with given fields: ctx, userID, mustReset
func (_m *UserRepository) SetMustResetPassword(ctx context.Context, userID uuid.UUID, mustReset bool) error {
	ret := _m.Called(ctx, userID, mustReset)

	if len(ret) == 0 {
		panic("no return value specified for SetMustResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, userID, mustReset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_SetMustResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMustResetPassword'
type UserRepository_SetMustResetPassword_Call struct {
	*mock.Call
}

// SetMustResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - mustReset bool
func (_e *UserRepository_Expecter) SetMustResetPassword(ctx interface{}, userID interface{}, mustReset interface{}) *UserRepository_SetMustResetPassword_Call {
	return &UserRepository_SetMustResetPassword_Call{Call: _e.mock.On("SetMustResetPassword", ctx, userID, mustReset)}
}

func (_c *UserRepository_SetMustResetPassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, mustReset bool)) *UserRepository_SetMustResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *UserRepository_SetMustResetPassword_Call) Return(_a0 error) *UserRepository_SetMustResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_SetMustResetPassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *UserRepository_SetMustResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *UserRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type UserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwordHash string
func (_e *UserRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *UserRepository_UpdatePassword_Call {
	return &UserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *UserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwordHash string)) *UserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_UpdatePassword_Call) Return(_a0 error) *UserRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *UserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
