// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// UserProfileRepository is an autogenerated mock type for the UserProfileRepository type
type UserProfileRepository struct {
	mock.Mock
}

type UserProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProfileRepository) EXPECT() *UserProfileRepository_Expecter {
	return &UserProfileRepository_Expecter{mock: &_m.Mock}
}

// CheckEmailExists provides a mock function with given fields: ctx, email, excludeUserID
func (_m *UserProfileRepository) CheckEmailExists(ctx context.Context, email string, excludeUserID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, email, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for CheckEmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (bool, error)); ok {
		return rf(ctx, email, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) bool); ok {
		r0 = rf(ctx, email, excludeUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, email, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_CheckEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEmailExists'
type UserProfileRepository_CheckEmailExists_Call struct {
	*mock.Call
}

// CheckEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - excludeUserID uuid.UUID
func (_e *UserProfileRepository_Expecter) CheckEmailExists(ctx interface{}, email interface{}, excludeUserID interface{}) *UserProfileRepository_CheckEmailExists_Call {
	return &UserProfileRepository_CheckEmailExists_Call{Call: _e.mock.On("CheckEmailExists", ctx, email, excludeUserID)}
}

func (_c *UserProfileRepository_CheckEmailExists_Call) Run(run func(ctx context.Context, email string, excludeUserID uuid.UUID)) *UserProfileRepository_CheckEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *UserProfileRepository_CheckEmailExists_Call) Return(_a0 bool, _a1 error) *UserProfileRepository_CheckEmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_CheckEmailExists_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (bool, error)) *UserProfileRepository_CheckEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *UserProfileRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (*entity.UserBasic, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.UserBasic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserBasic, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserBasic); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBasic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserProfileRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserProfileRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *UserProfileRepository_GetUserByID_Call {
	return &UserProfileRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *UserProfileRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserProfileRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserProfileRepository_GetUserByID_Call) Return(_a0 *entity.UserBasic, _a1 error) *UserProfileRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserBasic, error)) *UserProfileRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithPasswordByID provides a mock function with given fields: ctx, userID
func (_m *UserProfileRepository) GetUserWithPasswordByID(ctx context.Context, userID uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithPasswordByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_GetUserWithPasswordByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithPasswordByID'
type UserProfileRepository_GetUserWithPasswordByID_Call struct {
	*mock.Call
}

// GetUserWithPasswordByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserProfileRepository_Expecter) GetUserWithPasswordByID(ctx interface{}, userID interface{}) *UserProfileRepository_GetUserWithPasswordByID_Call {
	return &UserProfileRepository_GetUserWithPasswordByID_Call{Call: _e.mock.On("GetUserWithPasswordByID", ctx, userID)}
}

func (_c *UserProfileRepository_GetUserWithPasswordByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserProfileRepository_GetUserWithPasswordByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserProfileRepository_GetUserWithPasswordByID_Call) Return(_a0 *entity.User, _a1 error) *UserProfileRepository_GetUserWithPasswordByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_GetUserWithPasswordByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.User, error)) *UserProfileRepository_GetUserWithPasswordByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByOrganization provides a mock function with given fields: ctx, orgID
func (_m *UserProfileRepository) GetUsersByOrganization(ctx context.Context, orgID uuid.UUID) ([]entity.UserWithOrgRole, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByOrganization")
	}

	var r0 []entity.UserWithOrgRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_GetUsersByOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByOrganization'
type UserProfileRepository_GetUsersByOrganization_Call struct {
	*mock.Call
}

// GetUsersByOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *UserProfileRepository_Expecter) GetUsersByOrganization(ctx interface{}, orgID interface{}) *UserProfileRepository_GetUsersByOrganization_Call {
	return &UserProfileRepository_GetUsersByOrganization_Call{Call: _e.mock.On("GetUsersByOrganization", ctx, orgID)}
}

func (_c *UserProfileRepository_GetUsersByOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *UserProfileRepository_GetUsersByOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserProfileRepository_GetUsersByOrganization_Call) Return(_a0 []entity.UserWithOrgRole, _a1 error) *UserProfileRepository_GetUsersByOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_GetUsersByOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)) *UserProfileRepository_GetUsersByOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, orgID, query, limit
func (_m *UserProfileRepository) SearchUsers(ctx context.Context, orgID uuid.UUID, query string, limit int) ([]entity.UserBasic, error) {
	ret := _m.Called(ctx, orgID, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []entity.UserBasic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]entity.UserBasic, error)); ok {
		return rf(ctx, orgID, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []entity.UserBasic); ok {
		r0 = rf(ctx, orgID, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBasic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, orgID, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type UserProfileRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - query string
//   - limit int
func (_e *UserProfileRepository_Expecter) SearchUsers(ctx interface{}, orgID interface{}, query interface{}, limit interface{}) *UserProfileRepository_SearchUsers_Call {
	return &UserProfileRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, orgID, query, limit)}
}

func (_c *UserProfileRepository_SearchUsers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, query string, limit int)) *UserProfileRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *UserProfileRepository_SearchUsers_Call) Return(_a0 []entity.UserBasic, _a1 error) *UserProfileRepository_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_SearchUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, int) ([]entity.UserBasic, error)) *UserProfileRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *UserProfileRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProfileRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type UserProfileRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwordHash string
func (_e *UserProfileRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *UserProfileRepository_UpdatePassword_Call {
	return &UserProfileRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *UserProfileRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwordHash string)) *UserProfileRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserProfileRepository_UpdatePassword_Call) Return(_a0 error) *UserProfileRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserProfileRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *UserProfileRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, fullName, email
func (_m *UserProfileRepository) UpdateProfile(ctx context.Context, userID uuid.UUID, fullName string, email string) (*entity.User, error) {
	ret := _m.Called(ctx, userID, fullName, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*entity.User, error)); ok {
		return rf(ctx, userID, fullName, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *entity.User); ok {
		r0 = rf(ctx, userID, fullName, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, fullName, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProfileRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserProfileRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - fullName string
//   - email string
func (_e *UserProfileRepository_Expecter) UpdateProfile(ctx interface{}, userID interface{}, fullName interface{}, email interface{}) *UserProfileRepository_UpdateProfile_Call {
	return &UserProfileRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, fullName, email)}
}

func (_c *UserProfileRepository_UpdateProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, fullName string, email string)) *UserProfileRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserProfileRepository_UpdateProfile_Call) Return(_a0 *entity.User, _a1 error) *UserProfileRepository_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProfileRepository_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (*entity.User, error)) *UserProfileRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserProfileRepository creates a new instance of UserProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProfileRepository {
	mock := &UserProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
