// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// UserOrganizationRepository is an autogenerated mock type for the UserOrganizationRepository type
type UserOrganizationRepository struct {
	mock.Mock
}

type UserOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserOrganizationRepository) EXPECT() *UserOrganizationRepository_Expecter {
	return &UserOrganizationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userOrg
func (_m *UserOrganizationRepository) Create(ctx context.Context, userOrg *entity.UserOrganization) error {
	ret := _m.Called(ctx, userOrg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserOrganization) error); ok {
		r0 = rf(ctx, userOrg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserOrganizationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserOrganizationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userOrg *entity.UserOrganization
func (_e *UserOrganizationRepository_Expecter) Create(ctx interface{}, userOrg interface{}) *UserOrganizationRepository_Create_Call {
	return &UserOrganizationRepository_Create_Call{Call: _e.mock.On("Create", ctx, userOrg)}
}

func (_c *UserOrganizationRepository_Create_Call) Run(run func(ctx context.Context, userOrg *entity.UserOrganization)) *UserOrganizationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserOrganization))
	})
	return _c
}

func (_c *UserOrganizationRepository_Create_Call) Return(_a0 error) *UserOrganizationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserOrganizationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.UserOrganization) error) *UserOrganizationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, userID
func (_m *UserOrganizationRepository) Delete(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserOrganizationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserOrganizationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *UserOrganizationRepository_Expecter) Delete(ctx interface{}, orgID interface{}, userID interface{}) *UserOrganizationRepository_Delete_Call {
	return &UserOrganizationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, userID)}
}

func (_c *UserOrganizationRepository_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *UserOrganizationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *UserOrganizationRepository_Delete_Call) Return(_a0 error) *UserOrganizationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserOrganizationRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *UserOrganizationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndOrg provides a mock function with given fields: ctx, userID, orgID
func (_m *UserOrganizationRepository) GetByUserAndOrg(ctx context.Context, userID uuid.UUID, orgID uuid.UUID) (*entity.UserOrganization, error) {
	ret := _m.Called(ctx, userID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndOrg")
	}

	var r0 *entity.UserOrganization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.UserOrganization, error)); ok {
		return rf(ctx, userID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.UserOrganization); ok {
		r0 = rf(ctx, userID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserOrganization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserOrganizationRepository_GetByUserAndOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndOrg'
type UserOrganizationRepository_GetByUserAndOrg_Call struct {
	*mock.Call
}

// GetByUserAndOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orgID uuid.UUID
func (_e *UserOrganizationRepository_Expecter) GetByUserAndOrg(ctx interface{}, userID interface{}, orgID interface{}) *UserOrganizationRepository_GetByUserAndOrg_Call {
	return &UserOrganizationRepository_GetByUserAndOrg_Call{Call: _e.mock.On("GetByUserAndOrg", ctx, userID, orgID)}
}

func (_c *UserOrganizationRepository_GetByUserAndOrg_Call) Run(run func(ctx context.Context, userID uuid.UUID, orgID uuid.UUID)) *UserOrganizationRepository_GetByUserAndOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *UserOrganizationRepository_GetByUserAndOrg_Call) Return(_a0 *entity.UserOrganization, _a1 error) *UserOrganizationRepository_GetByUserAndOrg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserOrganizationRepository_GetByUserAndOrg_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.UserOrganization, error)) *UserOrganizationRepository_GetByUserAndOrg_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithOrganization provides a mock function with given fields: ctx, userID
func (_m *UserOrganizationRepository) GetUserWithOrganization(ctx context.Context, userID uuid.UUID) (*entity.UserWithOrganization, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithOrganization")
	}

	var r0 *entity.UserWithOrganization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserWithOrganization, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserWithOrganization); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserWithOrganization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserOrganizationRepository_GetUserWithOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithOrganization'
type UserOrganizationRepository_GetUserWithOrganization_Call struct {
	*mock.Call
}

// GetUserWithOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserOrganizationRepository_Expecter) GetUserWithOrganization(ctx interface{}, userID interface{}) *UserOrganizationRepository_GetUserWithOrganization_Call {
	return &UserOrganizationRepository_GetUserWithOrganization_Call{Call: _e.mock.On("GetUserWithOrganization", ctx, userID)}
}

func (_c *UserOrganizationRepository_GetUserWithOrganization_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserOrganizationRepository_GetUserWithOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserOrganizationRepository_GetUserWithOrganization_Call) Return(_a0 *entity.UserWithOrganization, _a1 error) *UserOrganizationRepository_GetUserWithOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserOrganizationRepository_GetUserWithOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserWithOrganization, error)) *UserOrganizationRepository_GetUserWithOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByOrganization provides a mock function with given fields: ctx, orgID
func (_m *UserOrganizationRepository) GetUsersByOrganization(ctx context.Context, orgID uuid.UUID) ([]entity.UserWithOrgRole, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByOrganization")
	}

	var r0 []entity.UserWithOrgRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserOrganizationRepository_GetUsersByOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByOrganization'
type UserOrganizationRepository_GetUsersByOrganization_Call struct {
	*mock.Call
}

// GetUsersByOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *UserOrganizationRepository_Expecter) GetUsersByOrganization(ctx interface{}, orgID interface{}) *UserOrganizationRepository_GetUsersByOrganization_Call {
	return &UserOrganizationRepository_GetUsersByOrganization_Call{Call: _e.mock.On("GetUsersByOrganization", ctx, orgID)}
}

func (_c *UserOrganizationRepository_GetUsersByOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *UserOrganizationRepository_GetUsersByOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserOrganizationRepository_GetUsersByOrganization_Call) Return(_a0 []entity.UserWithOrgRole, _a1 error) *UserOrganizationRepository_GetUsersByOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserOrganizationRepository_GetUsersByOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)) *UserOrganizationRepository_GetUsersByOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, orgID, userID, role
func (_m *UserOrganizationRepository) UpdateRole(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, orgID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserOrganizationRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type UserOrganizationRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *UserOrganizationRepository_Expecter) UpdateRole(ctx interface{}, orgID interface{}, userID interface{}, role interface{}) *UserOrganizationRepository_UpdateRole_Call {
	return &UserOrganizationRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, orgID, userID, role)}
}

func (_c *UserOrganizationRepository_UpdateRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, role string)) *UserOrganizationRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *UserOrganizationRepository_UpdateRole_Call) Return(_a0 error) *UserOrganizationRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserOrganizationRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *UserOrganizationRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserOrganizationRepository creates a new instance of UserOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserOrganizationRepository {
	mock := &UserOrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
