// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	organization "github.com/username/sekre-backend/internal/application/organization"

	types "github.com/username/sekre-backend/internal/domain/types"

	uuid "github.com/google/uuid"
)

// DivisionUsecase is an autogenerated mock type for the DivisionUsecase type
type DivisionUsecase struct {
	mock.Mock
}

type DivisionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *DivisionUsecase) EXPECT() *DivisionUsecase_Expecter {
	return &DivisionUsecase_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, orgID, divisionID, req
func (_m *DivisionUsecase) AddMember(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, req *organization.AddMemberRequest) error {
	ret := _m.Called(ctx, orgID, divisionID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *organization.AddMemberRequest) error); ok {
		r0 = rf(ctx, orgID, divisionID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionUsecase_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type DivisionUsecase_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - req *organization.AddMemberRequest
func (_e *DivisionUsecase_Expecter) AddMember(ctx interface{}, orgID interface{}, divisionID interface{}, req interface{}) *DivisionUsecase_AddMember_Call {
	return &DivisionUsecase_AddMember_Call{Call: _e.mock.On("AddMember", ctx, orgID, divisionID, req)}
}

func (_c *DivisionUsecase_AddMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, req *organization.AddMemberRequest)) *DivisionUsecase_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*organization.AddMemberRequest))
	})
	return _c
}

func (_c *DivisionUsecase_AddMember_Call) Return(_a0 error) *DivisionUsecase_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionUsecase_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *organization.AddMemberRequest) error) *DivisionUsecase_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orgID, req
func (_m *DivisionUsecase) Create(ctx context.Context, orgID uuid.UUID, req *organization.CreateDivisionRequest) (*entity.Division, error) {
	ret := _m.Called(ctx, orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *organization.CreateDivisionRequest) (*entity.Division, error)); ok {
		return rf(ctx, orgID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *organization.CreateDivisionRequest) *entity.Division); ok {
		r0 = rf(ctx, orgID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *organization.CreateDivisionRequest) error); ok {
		r1 = rf(ctx, orgID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DivisionUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - req *organization.CreateDivisionRequest
func (_e *DivisionUsecase_Expecter) Create(ctx interface{}, orgID interface{}, req interface{}) *DivisionUsecase_Create_Call {
	return &DivisionUsecase_Create_Call{Call: _e.mock.On("Create", ctx, orgID, req)}
}

func (_c *DivisionUsecase_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, req *organization.CreateDivisionRequest)) *DivisionUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*organization.CreateDivisionRequest))
	})
	return _c
}

func (_c *DivisionUsecase_Create_Call) Return(_a0 *entity.Division, _a1 error) *DivisionUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionUsecase_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *organization.CreateDivisionRequest) (*entity.Division, error)) *DivisionUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, id
func (_m *DivisionUsecase) Delete(ctx context.Context, orgID uuid.UUID, id uuid.UUID) error {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DivisionUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *DivisionUsecase_Expecter) Delete(ctx interface{}, orgID interface{}, id interface{}) *DivisionUsecase_Delete_Call {
	return &DivisionUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, id)}
}

func (_c *DivisionUsecase_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *DivisionUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionUsecase_Delete_Call) Return(_a0 error) *DivisionUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionUsecase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *DivisionUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, id
func (_m *DivisionUsecase) GetByID(ctx context.Context, orgID uuid.UUID, id uuid.UUID) (*entity.DivisionWithMembers, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.DivisionWithMembers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.DivisionWithMembers, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.DivisionWithMembers); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DivisionWithMembers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DivisionUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *DivisionUsecase_Expecter) GetByID(ctx interface{}, orgID interface{}, id interface{}) *DivisionUsecase_GetByID_Call {
	return &DivisionUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, id)}
}

func (_c *DivisionUsecase_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *DivisionUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionUsecase_GetByID_Call) Return(_a0 *entity.DivisionWithMembers, _a1 error) *DivisionUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionUsecase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.DivisionWithMembers, error)) *DivisionUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, orgID, divisionID
func (_m *DivisionUsecase) GetMembers(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID) ([]entity.UserWithRole, error) {
	ret := _m.Called(ctx, orgID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []entity.UserWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)); ok {
		return rf(ctx, orgID, divisionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []entity.UserWithRole); ok {
		r0 = rf(ctx, orgID, divisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, divisionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionUsecase_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type DivisionUsecase_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
func (_e *DivisionUsecase_Expecter) GetMembers(ctx interface{}, orgID interface{}, divisionID interface{}) *DivisionUsecase_GetMembers_Call {
	return &DivisionUsecase_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, orgID, divisionID)}
}

func (_c *DivisionUsecase_GetMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID)) *DivisionUsecase_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionUsecase_GetMembers_Call) Return(_a0 []entity.UserWithRole, _a1 error) *DivisionUsecase_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionUsecase_GetMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]entity.UserWithRole, error)) *DivisionUsecase_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersPaginated provides a mock function with given fields: ctx, orgID, divisionID, pagination
func (_m *DivisionUsecase) GetMembersPaginated(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, pagination types.PaginationParams) ([]entity.UserWithRole, int, error) {
	ret := _m.Called(ctx, orgID, divisionID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersPaginated")
	}

	var r0 []entity.UserWithRole
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) ([]entity.UserWithRole, int, error)); ok {
		return rf(ctx, orgID, divisionID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) []entity.UserWithRole); ok {
		r0 = rf(ctx, orgID, divisionID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, divisionID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionUsecase_GetMembersPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersPaginated'
type DivisionUsecase_GetMembersPaginated_Call struct {
	*mock.Call
}

// GetMembersPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - pagination types.PaginationParams
func (_e *DivisionUsecase_Expecter) GetMembersPaginated(ctx interface{}, orgID interface{}, divisionID interface{}, pagination interface{}) *DivisionUsecase_GetMembersPaginated_Call {
	return &DivisionUsecase_GetMembersPaginated_Call{Call: _e.mock.On("GetMembersPaginated", ctx, orgID, divisionID, pagination)}
}

func (_c *DivisionUsecase_GetMembersPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, pagination types.PaginationParams)) *DivisionUsecase_GetMembersPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(types.PaginationParams))
	})
	return _c
}

func (_c *DivisionUsecase_GetMembersPaginated_Call) Return(_a0 []entity.UserWithRole, _a1 int, _a2 error) *DivisionUsecase_GetMembersPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionUsecase_GetMembersPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, types.PaginationParams) ([]entity.UserWithRole, int, error)) *DivisionUsecase_GetMembersPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *DivisionUsecase) List(ctx context.Context, orgID uuid.UUID) ([]entity.Division, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Division, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Division); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DivisionUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *DivisionUsecase_Expecter) List(ctx interface{}, orgID interface{}) *DivisionUsecase_List_Call {
	return &DivisionUsecase_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *DivisionUsecase_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *DivisionUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionUsecase_List_Call) Return(_a0 []entity.Division, _a1 error) *DivisionUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionUsecase_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Division, error)) *DivisionUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function with given fields: ctx, orgID, pagination
func (_m *DivisionUsecase) ListPaginated(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams) ([]entity.Division, int, error) {
	ret := _m.Called(ctx, orgID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []entity.Division
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.Division, int, error)); ok {
		return rf(ctx, orgID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.PaginationParams) []entity.Division); ok {
		r0 = rf(ctx, orgID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionUsecase_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type DivisionUsecase_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - pagination types.PaginationParams
func (_e *DivisionUsecase_Expecter) ListPaginated(ctx interface{}, orgID interface{}, pagination interface{}) *DivisionUsecase_ListPaginated_Call {
	return &DivisionUsecase_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, orgID, pagination)}
}

func (_c *DivisionUsecase_ListPaginated_Call) Run(run func(ctx context.Context, orgID uuid.UUID, pagination types.PaginationParams)) *DivisionUsecase_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(types.PaginationParams))
	})
	return _c
}

func (_c *DivisionUsecase_ListPaginated_Call) Return(_a0 []entity.Division, _a1 int, _a2 error) *DivisionUsecase_ListPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionUsecase_ListPaginated_Call) RunAndReturn(run func(context.Context, uuid.UUID, types.PaginationParams) ([]entity.Division, int, error)) *DivisionUsecase_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginatedFiltered provides a mock function with given fields: ctx, orgID, search, pagination
func (_m *DivisionUsecase) ListPaginatedFiltered(ctx context.Context, orgID uuid.UUID, search *string, pagination types.PaginationParams) ([]entity.Division, int, error) {
	ret := _m.Called(ctx, orgID, search, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginatedFiltered")
	}

	var r0 []entity.Division
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, types.PaginationParams) ([]entity.Division, int, error)); ok {
		return rf(ctx, orgID, search, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, types.PaginationParams) []entity.Division); ok {
		r0 = rf(ctx, orgID, search, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, types.PaginationParams) int); ok {
		r1 = rf(ctx, orgID, search, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *string, types.PaginationParams) error); ok {
		r2 = rf(ctx, orgID, search, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionUsecase_ListPaginatedFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginatedFiltered'
type DivisionUsecase_ListPaginatedFiltered_Call struct {
	*mock.Call
}

// ListPaginatedFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - search *string
//   - pagination types.PaginationParams
func (_e *DivisionUsecase_Expecter) ListPaginatedFiltered(ctx interface{}, orgID interface{}, search interface{}, pagination interface{}) *DivisionUsecase_ListPaginatedFiltered_Call {
	return &DivisionUsecase_ListPaginatedFiltered_Call{Call: _e.mock.On("ListPaginatedFiltered", ctx, orgID, search, pagination)}
}

func (_c *DivisionUsecase_ListPaginatedFiltered_Call) Run(run func(ctx context.Context, orgID uuid.UUID, search *string, pagination types.PaginationParams)) *DivisionUsecase_ListPaginatedFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(types.PaginationParams))
	})
	return _c
}

func (_c *DivisionUsecase_ListPaginatedFiltered_Call) Return(_a0 []entity.Division, _a1 int, _a2 error) *DivisionUsecase_ListPaginatedFiltered_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionUsecase_ListPaginatedFiltered_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, types.PaginationParams) ([]entity.Division, int, error)) *DivisionUsecase_ListPaginatedFiltered_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, divisionID, userID
func (_m *DivisionUsecase) RemoveMember(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, divisionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionUsecase_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type DivisionUsecase_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
func (_e *DivisionUsecase_Expecter) RemoveMember(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}) *DivisionUsecase_RemoveMember_Call {
	return &DivisionUsecase_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, divisionID, userID)}
}

func (_c *DivisionUsecase_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID)) *DivisionUsecase_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *DivisionUsecase_RemoveMember_Call) Return(_a0 error) *DivisionUsecase_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionUsecase_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *DivisionUsecase_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, id, req
func (_m *DivisionUsecase) Update(ctx context.Context, orgID uuid.UUID, id uuid.UUID, req *organization.UpdateDivisionRequest) (*entity.Division, error) {
	ret := _m.Called(ctx, orgID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *organization.UpdateDivisionRequest) (*entity.Division, error)); ok {
		return rf(ctx, orgID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *organization.UpdateDivisionRequest) *entity.Division); ok {
		r0 = rf(ctx, orgID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *organization.UpdateDivisionRequest) error); ok {
		r1 = rf(ctx, orgID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DivisionUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
//   - req *organization.UpdateDivisionRequest
func (_e *DivisionUsecase_Expecter) Update(ctx interface{}, orgID interface{}, id interface{}, req interface{}) *DivisionUsecase_Update_Call {
	return &DivisionUsecase_Update_Call{Call: _e.mock.On("Update", ctx, orgID, id, req)}
}

func (_c *DivisionUsecase_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID, req *organization.UpdateDivisionRequest)) *DivisionUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*organization.UpdateDivisionRequest))
	})
	return _c
}

func (_c *DivisionUsecase_Update_Call) Return(_a0 *entity.Division, _a1 error) *DivisionUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionUsecase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *organization.UpdateDivisionRequest) (*entity.Division, error)) *DivisionUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, orgID, divisionID, userID, role
func (_m *DivisionUsecase) UpdateMemberRole(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, orgID, divisionID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, divisionID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionUsecase_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type DivisionUsecase_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - divisionID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *DivisionUsecase_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, divisionID interface{}, userID interface{}, role interface{}) *DivisionUsecase_UpdateMemberRole_Call {
	return &DivisionUsecase_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, divisionID, userID, role)}
}

func (_c *DivisionUsecase_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, divisionID uuid.UUID, userID uuid.UUID, role string)) *DivisionUsecase_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *DivisionUsecase_UpdateMemberRole_Call) Return(_a0 error) *DivisionUsecase_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionUsecase_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error) *DivisionUsecase_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewDivisionUsecase creates a new instance of DivisionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDivisionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DivisionUsecase {
	mock := &DivisionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
