// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// OrganizationUsecase is an autogenerated mock type for the OrganizationUsecase type
type OrganizationUsecase struct {
	mock.Mock
}

type OrganizationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationUsecase) EXPECT() *OrganizationUsecase_Expecter {
	return &OrganizationUsecase_Expecter{mock: &_m.Mock}
}

// DeleteOrganization provides a mock function with given fields: ctx, orgID, userID
func (_m *OrganizationUsecase) DeleteOrganization(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationUsecase_DeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganization'
type OrganizationUsecase_DeleteOrganization_Call struct {
	*mock.Call
}

// DeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *OrganizationUsecase_Expecter) DeleteOrganization(ctx interface{}, orgID interface{}, userID interface{}) *OrganizationUsecase_DeleteOrganization_Call {
	return &OrganizationUsecase_DeleteOrganization_Call{Call: _e.mock.On("DeleteOrganization", ctx, orgID, userID)}
}

func (_c *OrganizationUsecase_DeleteOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *OrganizationUsecase_DeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *OrganizationUsecase_DeleteOrganization_Call) Return(_a0 error) *OrganizationUsecase_DeleteOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUsecase_DeleteOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *OrganizationUsecase_DeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganization provides a mock function with given fields: ctx, orgID, userID, name
func (_m *OrganizationUsecase) UpdateOrganization(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, name string) (*entity.Organization, error) {
	ret := _m.Called(ctx, orgID, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 *entity.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*entity.Organization, error)); ok {
		return rf(ctx, orgID, userID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *entity.Organization); ok {
		r0 = rf(ctx, orgID, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, orgID, userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_UpdateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganization'
type OrganizationUsecase_UpdateOrganization_Call struct {
	*mock.Call
}

// UpdateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - name string
func (_e *OrganizationUsecase_Expecter) UpdateOrganization(ctx interface{}, orgID interface{}, userID interface{}, name interface{}) *OrganizationUsecase_UpdateOrganization_Call {
	return &OrganizationUsecase_UpdateOrganization_Call{Call: _e.mock.On("UpdateOrganization", ctx, orgID, userID, name)}
}

func (_c *OrganizationUsecase_UpdateOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, name string)) *OrganizationUsecase_UpdateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_UpdateOrganization_Call) Return(_a0 *entity.Organization, _a1 error) *OrganizationUsecase_UpdateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_UpdateOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*entity.Organization, error)) *OrganizationUsecase_UpdateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationUsecase creates a new instance of OrganizationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationUsecase {
	mock := &OrganizationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
