// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	task "github.com/username/sekre-backend/internal/application/task"

	uuid "github.com/google/uuid"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

type TaskUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskUsecase) EXPECT() *TaskUsecase_Expecter {
	return &TaskUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orgID, req
func (_m *TaskUsecase) Create(ctx context.Context, orgID uuid.UUID, req *task.CreateTaskRequest) (*entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *task.CreateTaskRequest) (*entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *task.CreateTaskRequest) *entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *task.CreateTaskRequest) error); ok {
		r1 = rf(ctx, orgID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - req *task.CreateTaskRequest
func (_e *TaskUsecase_Expecter) Create(ctx interface{}, orgID interface{}, req interface{}) *TaskUsecase_Create_Call {
	return &TaskUsecase_Create_Call{Call: _e.mock.On("Create", ctx, orgID, req)}
}

func (_c *TaskUsecase_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, req *task.CreateTaskRequest)) *TaskUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*task.CreateTaskRequest))
	})
	return _c
}

func (_c *TaskUsecase_Create_Call) Return(_a0 *entity.TaskWithAssignee, _a1 error) *TaskUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *task.CreateTaskRequest) (*entity.TaskWithAssignee, error)) *TaskUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, id
func (_m *TaskUsecase) Delete(ctx context.Context, orgID uuid.UUID, id uuid.UUID) error {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *TaskUsecase_Expecter) Delete(ctx interface{}, orgID interface{}, id interface{}) *TaskUsecase_Delete_Call {
	return &TaskUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, id)}
}

func (_c *TaskUsecase_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *TaskUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskUsecase_Delete_Call) Return(_a0 error) *TaskUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskUsecase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *TaskUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, id
func (_m *TaskUsecase) GetByID(ctx context.Context, orgID uuid.UUID, id uuid.UUID) (*entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TaskUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
func (_e *TaskUsecase_Expecter) GetByID(ctx interface{}, orgID interface{}, id interface{}) *TaskUsecase_GetByID_Call {
	return &TaskUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, id)}
}

func (_c *TaskUsecase_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID)) *TaskUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TaskUsecase_GetByID_Call) Return(_a0 *entity.TaskWithAssignee, _a1 error) *TaskUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.TaskWithAssignee, error)) *TaskUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, filters
func (_m *TaskUsecase) List(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters) ([]entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters) ([]entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskFilters) []entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.TaskFilters) error); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - filters entity.TaskFilters
func (_e *TaskUsecase_Expecter) List(ctx interface{}, orgID interface{}, filters interface{}) *TaskUsecase_List_Call {
	return &TaskUsecase_List_Call{Call: _e.mock.On("List", ctx, orgID, filters)}
}

func (_c *TaskUsecase_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID, filters entity.TaskFilters)) *TaskUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TaskFilters))
	})
	return _c
}

func (_c *TaskUsecase_List_Call) Return(_a0 []entity.TaskWithAssignee, _a1 error) *TaskUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.TaskFilters) ([]entity.TaskWithAssignee, error)) *TaskUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, id, req
func (_m *TaskUsecase) Update(ctx context.Context, orgID uuid.UUID, id uuid.UUID, req *task.UpdateTaskRequest) (*entity.TaskWithAssignee, error) {
	ret := _m.Called(ctx, orgID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.TaskWithAssignee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *task.UpdateTaskRequest) (*entity.TaskWithAssignee, error)); ok {
		return rf(ctx, orgID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *task.UpdateTaskRequest) *entity.TaskWithAssignee); ok {
		r0 = rf(ctx, orgID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskWithAssignee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *task.UpdateTaskRequest) error); ok {
		r1 = rf(ctx, orgID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
//   - req *task.UpdateTaskRequest
func (_e *TaskUsecase_Expecter) Update(ctx interface{}, orgID interface{}, id interface{}, req interface{}) *TaskUsecase_Update_Call {
	return &TaskUsecase_Update_Call{Call: _e.mock.On("Update", ctx, orgID, id, req)}
}

func (_c *TaskUsecase_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID, req *task.UpdateTaskRequest)) *TaskUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*task.UpdateTaskRequest))
	})
	return _c
}

func (_c *TaskUsecase_Update_Call) Return(_a0 *entity.TaskWithAssignee, _a1 error) *TaskUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *task.UpdateTaskRequest) (*entity.TaskWithAssignee, error)) *TaskUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orgID, id, status
func (_m *TaskUsecase) UpdateStatus(ctx context.Context, orgID uuid.UUID, id uuid.UUID, status string) error {
	ret := _m.Called(ctx, orgID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orgID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskUsecase_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type TaskUsecase_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - id uuid.UUID
//   - status string
func (_e *TaskUsecase_Expecter) UpdateStatus(ctx interface{}, orgID interface{}, id interface{}, status interface{}) *TaskUsecase_UpdateStatus_Call {
	return &TaskUsecase_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orgID, id, status)}
}

func (_c *TaskUsecase_UpdateStatus_Call) Run(run func(ctx context.Context, orgID uuid.UUID, id uuid.UUID, status string)) *TaskUsecase_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TaskUsecase_UpdateStatus_Call) Return(_a0 error) *TaskUsecase_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskUsecase_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *TaskUsecase_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
