// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/username/sekre-backend/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

type UserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUsecase) EXPECT() *UserUsecase_Expecter {
	return &UserUsecase_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, currentPassword, newPassword
func (_m *UserUsecase) ChangePassword(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserUsecase_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserUsecase_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentPassword string
//   - newPassword string
func (_e *UserUsecase_Expecter) ChangePassword(ctx interface{}, userID interface{}, currentPassword interface{}, newPassword interface{}) *UserUsecase_ChangePassword_Call {
	return &UserUsecase_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *UserUsecase_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string)) *UserUsecase_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserUsecase_ChangePassword_Call) Return(_a0 error) *UserUsecase_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserUsecase_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *UserUsecase_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUsers provides a mock function with given fields: ctx, orgID
func (_m *UserUsecase) GetOrganizationUsers(ctx context.Context, orgID uuid.UUID) ([]entity.UserWithOrgRole, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUsers")
	}

	var r0 []entity.UserWithOrgRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserWithOrgRole); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserWithOrgRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUsecase_GetOrganizationUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUsers'
type UserUsecase_GetOrganizationUsers_Call struct {
	*mock.Call
}

// GetOrganizationUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *UserUsecase_Expecter) GetOrganizationUsers(ctx interface{}, orgID interface{}) *UserUsecase_GetOrganizationUsers_Call {
	return &UserUsecase_GetOrganizationUsers_Call{Call: _e.mock.On("GetOrganizationUsers", ctx, orgID)}
}

func (_c *UserUsecase_GetOrganizationUsers_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *UserUsecase_GetOrganizationUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserUsecase_GetOrganizationUsers_Call) Return(_a0 []entity.UserWithOrgRole, _a1 error) *UserUsecase_GetOrganizationUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUsecase_GetOrganizationUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.UserWithOrgRole, error)) *UserUsecase_GetOrganizationUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, orgID, query
func (_m *UserUsecase) SearchUsers(ctx context.Context, orgID uuid.UUID, query string) ([]entity.UserBasic, error) {
	ret := _m.Called(ctx, orgID, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []entity.UserBasic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]entity.UserBasic, error)); ok {
		return rf(ctx, orgID, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []entity.UserBasic); ok {
		r0 = rf(ctx, orgID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBasic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, orgID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUsecase_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type UserUsecase_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - query string
func (_e *UserUsecase_Expecter) SearchUsers(ctx interface{}, orgID interface{}, query interface{}) *UserUsecase_SearchUsers_Call {
	return &UserUsecase_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, orgID, query)}
}

func (_c *UserUsecase_SearchUsers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, query string)) *UserUsecase_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *UserUsecase_SearchUsers_Call) Return(_a0 []entity.UserBasic, _a1 error) *UserUsecase_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUsecase_SearchUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]entity.UserBasic, error)) *UserUsecase_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, fullName, email
func (_m *UserUsecase) UpdateProfile(ctx context.Context, userID uuid.UUID, fullName string, email string) (*entity.User, error) {
	ret := _m.Called(ctx, userID, fullName, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*entity.User, error)); ok {
		return rf(ctx, userID, fullName, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *entity.User); ok {
		r0 = rf(ctx, userID, fullName, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, fullName, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUsecase_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserUsecase_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - fullName string
//   - email string
func (_e *UserUsecase_Expecter) UpdateProfile(ctx interface{}, userID interface{}, fullName interface{}, email interface{}) *UserUsecase_UpdateProfile_Call {
	return &UserUsecase_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, fullName, email)}
}

func (_c *UserUsecase_UpdateProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, fullName string, email string)) *UserUsecase_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserUsecase_UpdateProfile_Call) Return(_a0 *entity.User, _a1 error) *UserUsecase_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUsecase_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (*entity.User, error)) *UserUsecase_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
